<?php
/**
 *
 * ÅyäGï∂éöÉfÅ[É^ÉtÉ@ÉCÉãÅz
 *
 * Ç±ÇÃÉfÅ[É^ÇÕi-ModeÇÃäGï∂éöÇ…ëŒâûÇ∑ÇÈëºÉLÉÉÉäÉAÇÃäGï∂éöÇäiî[ÇµÇΩÉfÅ[É^Ç≈Ç∑.
 * EzWebÇ∆WillcomÇÃÉfÅ[É^ÇÕi-ModeÇÃäGï∂éöÇgatewayÇ™é©ìÆïœä∑ÇµÇΩÇ‡ÇÃÇ≈Ç∑.
 * àÍïîïœä∑Ç≈Ç´Ç∏Ç…ãÛï∂éöóÒÇ…Ç»Ç¡ÇƒÇ¢ÇÈÇ‡ÇÃÇ™Ç†ÇËÇ‹Ç∑.
 * SoftbankÇÃäGï∂éöÇÕëŒâûÇ∑ÇÈÇ≈Ç†ÇÎÇ§äGï∂éöÇäiî[ÇµÇΩÇ‡ÇÃÇÃÇΩÇﬂÅA
 * àÍïîï\åªÇ™è„éËÇ≠Ç†Ç¡ÇƒÇ¢Ç»Ç¢â¬î\ê´Ç™Ç†ÇËÇ‹Ç∑.
 * i-ModeÇ≈íËã`Ç≥ÇÍÇƒÇ¢ÇÈäGï∂éöï\åªà»äOÇÃÇ‡ÇÃÇ
 * i-Modeà»äOÇ≈égópÇµÇΩÇ¢èÍçáÇÕíºê⁄ÉfÅ[É^ÇñÑÇﬂçûÇﬁïKóvÇ™Ç†ÇËÇ‹Ç∑.
 * 
 * ãÔëÃìIÇ…Ç«ÇÃÇÊÇ§Ç»äGï∂éöÇ™ï\é¶Ç≥ÇÍÇÈÇ©ÇÕPHP_MOD/doc/emoji.phpÇégópÇµÇƒämîFÇ≈Ç´Ç‹Ç∑.
 * 
 * @package default
 * @version $Id: CYUtilsEmoji.inc.php,v 1.1 2007/03/16 02:44:46 hiroaki_tanaka Exp $
 */
 
 
/**
 * 'CYDeviceInfoFile.inc.php' ÇÃ ÉCÉìÉNÉãÅ[Éh
 */ 
require_once dirname(__FILE__). '/CYUtilsDevice.inc.php';


$EMOJI = array();
$EMOJI_I = array();
$EMOJI_V = array();
$EMOJI_E = array();
$EMOJI_W = array();

$hdml_flg = getHdmlFlag();

if ( $CARRIER_ID === 'i' ) {

    $EMOJI['sun']            = '¯ü';
    $EMOJI['cloud']          = '¯†';
    $EMOJI['rain']           = '¯°';
    $EMOJI['snow']           = '¯¢';
    $EMOJI['thunder']        = '¯£';
    $EMOJI['typhoon']        = '¯§';
    $EMOJI['fog']            = '¯•';
    $EMOJI['light_rain']     = '¯¶';
    $EMOJI['ram']            = '¯ß';
    $EMOJI['bull']           = '¯®';
    $EMOJI['twins']          = '¯©';
    $EMOJI['crab']           = '¯™';
    $EMOJI['lion']           = '¯´';
    $EMOJI['virgin']         = '¯¨';
    $EMOJI['balance']        = '¯≠';
    $EMOJI['scorpion']       = '¯Æ';
    $EMOJI['archer']         = '¯Ø';
    $EMOJI['goat']           = '¯∞';
    $EMOJI['water_bearer']   = '¯±';
    $EMOJI['fishes']         = '¯≤';
    $EMOJI['sports']         = '¯≥';
    $EMOJI['baseball']       = '¯¥';
    $EMOJI['golf']           = '¯µ';
    $EMOJI['tennis']         = '¯∂';
    $EMOJI['soccer']         = '¯∑';
    $EMOJI['ski']            = '¯∏';
    $EMOJI['basketball']     = '¯π';
    $EMOJI['flag']           = '¯∫';
    $EMOJI['pocket_bell']    = '¯ª';
    $EMOJI['train']          = '¯º';
    $EMOJI['subway']         = '¯Ω';
    $EMOJI['shinkansen']     = '¯æ';
    $EMOJI['car']            = '¯ø';
    $EMOJI['car_2']          = '¯¿';
    $EMOJI['bus']            = '¯¡';
    $EMOJI['ship']           = '¯¬';
    $EMOJI['airplane']       = '¯√';
    $EMOJI['house']          = '¯ƒ';
    $EMOJI['building']       = '¯≈';
    $EMOJI['post_office']    = '¯∆';
    $EMOJI['hospital']       = '¯«';
    $EMOJI['bank']           = '¯»';
    $EMOJI['atm']            = '¯…';
    $EMOJI['hotel']          = '¯ ';
    $EMOJI['cvs']            = '¯À';
    $EMOJI['gas_station']    = '¯Ã';
    $EMOJI['parking']        = '¯Õ';
    $EMOJI['signal']         = '¯Œ';
    $EMOJI['toilet']         = '¯œ';
    $EMOJI['restaurant']     = '¯–';
    $EMOJI['cafe']           = '¯—';
    $EMOJI['bar']            = '¯“';
    $EMOJI['beer']           = '¯”';
    $EMOJI['first_food']     = '¯‘';
    $EMOJI['boutique']       = '¯’';
    $EMOJI['beauty_salon']   = '¯÷';
    $EMOJI['karaoke']        = '¯◊';
    $EMOJI['movie']          = '¯ÿ';
    $EMOJI['right_up']       = '¯Ÿ';
    $EMOJI['amusement_park'] = '¯⁄';
    $EMOJI['music']          = '¯€';
    $EMOJI['art']            = '¯‹';
    $EMOJI['drama']          = '¯›';
    $EMOJI['event']          = '¯ﬁ';
    $EMOJI['ticket']         = '¯ﬂ';
    $EMOJI['smoking']        = '¯‡';
    $EMOJI['no_smoking']     = '¯·';
    $EMOJI['camera']         = '¯‚';
    $EMOJI['bag']            = '¯„';
    $EMOJI['book']           = '¯‰';
    $EMOJI['ribbon']         = '¯Â';
    $EMOJI['present']        = '¯Ê';
    $EMOJI['birthday']       = '¯Á';
    $EMOJI['telephone']      = '¯Ë';
    $EMOJI['mobile']         = '¯È';
    $EMOJI['memo']           = '¯Í';
    $EMOJI['tv']             = '¯Î';
    $EMOJI['game']           = '¯Ï';
    $EMOJI['cd']             = '¯Ì';
    $EMOJI['heart']          = '¯Ó';
    $EMOJI['spade']          = '¯Ô';
    $EMOJI['diamond']        = '¯';
    $EMOJI['clubs']          = '¯Ò';
    $EMOJI['eye']            = '¯Ú';
    $EMOJI['ear']            = '¯Û';
    $EMOJI['goo']            = '¯Ù';
    $EMOJI['choki']          = '¯ı';
    $EMOJI['par']            = '¯ˆ';
    $EMOJI['right_down']     = '¯˜';
    $EMOJI['left_up']        = '¯¯';
    $EMOJI['foot']           = '¯˘';
    $EMOJI['shoes']          = '¯˙';
    $EMOJI['glasses']        = '¯˚';
    $EMOJI['wheelchair']     = '¯¸';
    $EMOJI['new_moon']       = '˘@';
    $EMOJI['chip_moon']      = '˘A';
    $EMOJI['half_moon']      = '˘B';
    $EMOJI['crescent_moon']  = '˘C';
    $EMOJI['full_moon']      = '˘D';
    $EMOJI['dog']            = '˘E';
    $EMOJI['cat']            = '˘F';
    $EMOJI['resort']         = '˘G';
    $EMOJI['xmas']           = '˘H';
    $EMOJI['left_down']      = '˘I';
    $EMOJI['kachinko']       = '˘P';
    $EMOJI['pouch']          = '˘Q';
    $EMOJI['pen']            = '˘R';
    $EMOJI['shadow']         = '˘U';
    $EMOJI['chair']          = '˘V';
    $EMOJI['night']          = '˘W';
    $EMOJI['soon']           = '˘[';
    $EMOJI['on']             = '˘\\';
    $EMOJI['end']            = '˘]';
    $EMOJI['clock']          = '˘^';
    $EMOJI['phone_to']       = '˘r';
    $EMOJI['mail_to']        = '˘s';
    $EMOJI['fax_to']         = '˘t';
    $EMOJI['carrier']        = '˘u';
    $EMOJI['carrier_2']      = '˘v';
    $EMOJI['mail']           = '˘w';
    $EMOJI['offer']          = '˘x';
    $EMOJI['point']          = '˘y';
    $EMOJI['yen']            = '˘z';
    $EMOJI['free']           = '˘{';
    $EMOJI['id']             = '˘|';
    $EMOJI['password']       = '˘}';
    $EMOJI['return']         = '˘~';
    $EMOJI['clear']          = '˘Ä';
    $EMOJI['search']         = '˘Å';
    $EMOJI['new']            = '˘Ç';
    $EMOJI['place']          = '˘É';
    $EMOJI['free_dial']      = '˘Ñ';
    $EMOJI['sharp_dial']     = '˘Ö';
    $EMOJI['mob_q']          = '˘Ü';
    $EMOJI['1']              = '˘á';
    $EMOJI['2']              = '˘à';
    $EMOJI['3']              = '˘â';
    $EMOJI['4']              = '˘ä';
    $EMOJI['5']              = '˘ã';
    $EMOJI['6']              = '˘å';
    $EMOJI['7']              = '˘ç';
    $EMOJI['8']              = '˘é';
    $EMOJI['9']              = '˘è';
    $EMOJI['0']              = '˘ê';
    $EMOJI['heart_black']    = '˘ë';
    $EMOJI['heart_wave']     = '˘í';
    $EMOJI['heart_break']    = '˘ì';
    $EMOJI['hearts']         = '˘î';
    $EMOJI['face_smile']     = '˘ï';
    $EMOJI['face_angry']     = '˘ñ';
    $EMOJI['face_deject']    = '˘ó';
    $EMOJI['face_sad']       = '˘ò';
    $EMOJI['face_swing']     = '˘ô';
    $EMOJI['good']           = '˘ö';
    $EMOJI['cheerful']       = '˘õ';
    $EMOJI['feel_good']      = '˘ú';
    $EMOJI['cute']           = '˘ù';
    $EMOJI['kiss']           = '˘û';
    $EMOJI['shine']          = '˘ü';
    $EMOJI['spark']          = '˘†';
    $EMOJI['anger']          = '˘°';
    $EMOJI['punch']          = '˘¢';
    $EMOJI['bomb']           = '˘£';
    $EMOJI['mood']           = '˘§';
    $EMOJI['bad']            = '˘•';
    $EMOJI['sleep']          = '˘¶';
    $EMOJI['exc']            = '˘ß';
    $EMOJI['exc_que']        = '˘®';
    $EMOJI['exc_2']          = '˘©';
    $EMOJI['shock']          = '˘™';
    $EMOJI['sweat']          = '˘´';
    $EMOJI['sweat_2']        = '˘¨';
    $EMOJI['dash']           = '˘≠';
    $EMOJI['long_vowel']     = '˘Æ';
    $EMOJI['long_vowel_2']   = '˘Ø';
    $EMOJI['ok']             = '˘∞';
    $EMOJI['appli']          = '˘±';
    $EMOJI['appli_2']        = '˘≤';
    $EMOJI['t-shirts']       = '˘≥';
    $EMOJI['wallet']         = '˘¥';
    $EMOJI['makeup']         = '˘µ';
    $EMOJI['jeans']          = '˘∂';
    $EMOJI['snow_board']     = '˘∑';
    $EMOJI['chapel']         = '˘∏';
    $EMOJI['door']           = '˘π';
    $EMOJI['dollar']         = '˘∫';
    $EMOJI['pc']             = '˘ª';
    $EMOJI['love_letter']    = '˘º';
    $EMOJI['wrench']         = '˘Ω';
    $EMOJI['pencil']         = '˘æ';
    $EMOJI['crown']          = '˘ø';
    $EMOJI['ring']           = '˘¿';
    $EMOJI['sandglass']      = '˘¡';
    $EMOJI['bicycle']        = '˘¬';
    $EMOJI['teacup']         = '˘√';
    $EMOJI['watch']          = '˘ƒ';
    $EMOJI['face_think']     = '˘≈';
    $EMOJI['face_peace']     = '˘∆';
    $EMOJI['face_hurry']     = '˘«';
    $EMOJI['face_hurry_2']   = '˘»';
    $EMOJI['face_angry_2']   = '˘…';
    $EMOJI['face_poker']     = '˘ ';
    $EMOJI['face_heart']     = '˘À';
    $EMOJI['finger']         = '˘Ã';
    $EMOJI['face_joke']      = '˘Õ';
    $EMOJI['face_wink']      = '˘Œ';
    $EMOJI['face_happy']     = '˘œ';
    $EMOJI['face_patience']  = '˘–';
    $EMOJI['cat_2']          = '˘—';
    $EMOJI['face_cry']       = '˘“';
    $EMOJI['tear']           = '˘”';
    $EMOJI['ng']             = '˘‘';
    $EMOJI['clip']           = '˘’';
    $EMOJI['copyright']      = '˘÷';
    $EMOJI['tm']             = '˘◊';
    $EMOJI['runner']         = '˘ÿ';
    $EMOJI['secret']         = '˘Ÿ';
    $EMOJI['recycling']      = '˘⁄';
    $EMOJI['regist']         = '˘€';
    $EMOJI['warning']        = '˘‹';
    $EMOJI['prohibition']    = '˘›';
    $EMOJI['empty']          = '˘ﬁ';
    $EMOJI['success']        = '˘ﬂ';
    $EMOJI['full']           = '˘‡';
    $EMOJI['right_left']     = '˘·';
    $EMOJI['up_down']        = '˘‚';
    $EMOJI['school']         = '˘„';
    $EMOJI['wave']           = '˘‰';
    $EMOJI['mountain']       = '˘Â';
    $EMOJI['clover']         = '˘Ê';
    $EMOJI['cherry']         = '˘Á';
    $EMOJI['tulip']          = '˘Ë';
    $EMOJI['banana']         = '˘È';
    $EMOJI['apple']          = '˘Í';
    $EMOJI['leaf']           = '˘Î';
    $EMOJI['maple']          = '˘Ï';
    $EMOJI['cherry_blossom'] = '˘Ì';
    $EMOJI['rice_ball']      = '˘Ó';
    $EMOJI['cake']           = '˘Ô';
    $EMOJI['sake']           = '˘';
    $EMOJI['bowl']           = '˘Ò';
    $EMOJI['pan']            = '˘Ú';
    $EMOJI['snail']          = '˘Û';
    $EMOJI['baby_bird']      = '˘Ù';
    $EMOJI['penguin']        = '˘ı';
    $EMOJI['fish']           = '˘ˆ';
    $EMOJI['face_delicious'] = '˘˜';
    $EMOJI['face_foppish']   = '˘¯';
    $EMOJI['horse']          = '˘˘';
    $EMOJI['pig']            = '˘˙';
    $EMOJI['wine']           = '˘˚';
    $EMOJI['face_let_down']  = '˘¸';

} elseif ( $CARRIER_ID === 'v' ) {

    $EMOJI['sun']            = '$Gj';
    $EMOJI['cloud']          = '$Gi';
    $EMOJI['rain']           = '$Gk';
    $EMOJI['snow']           = '$Gh';
    $EMOJI['thunder']        = '$E]';
    $EMOJI['typhoon']        = '$E]';
    $EMOJI['fog']            = '$Gi';
    $EMOJI['light_rain']     = '$Gk';
    $EMOJI['ram']            = '$F_';
    $EMOJI['bull']           = '$F`';
    $EMOJI['twins']          = '$Fa';
    $EMOJI['crab']           = '$Fb';
    $EMOJI['lion']           = '$Fc';
    $EMOJI['virgin']         = '$Fd';
    $EMOJI['balance']        = '$Fe';
    $EMOJI['scorpion']       = '$Ff';
    $EMOJI['archer']         = '$Fg';
    $EMOJI['goat']           = '$Fh';
    $EMOJI['water_bearer']   = '$Fi';
    $EMOJI['fishes']         = '$Fj';
    $EMOJI['sports']         = '$G&';
    $EMOJI['baseball']       = '$G6';
    $EMOJI['golf']           = '$G4';
    $EMOJI['tennis']         = '$G5';
    $EMOJI['soccer']         = '$G8';
    $EMOJI['ski']            = '$G3';
    $EMOJI['basketball']     = '$E5';
    $EMOJI['flag']           = '$ER';
    $EMOJI['pocket_bell']    = '$G*';
    $EMOJI['train']          = '$G>';
    $EMOJI['subway']         = '$G>';
    $EMOJI['shinkansen']     = '$G?';
    $EMOJI['car']            = '$G;';
    $EMOJI['car_2']          = '$G;';
    $EMOJI['bus']            = '$Ey';
    $EMOJI['ship']           = '$F"';
    $EMOJI['airplane']       = '$G=';
    $EMOJI['house']          = '$GV';
    $EMOJI['building']       = '$GX';
    $EMOJI['post_office']    = '$Es';
    $EMOJI['hospital']       = '$Eu';
    $EMOJI['bank']           = '$Em';
    $EMOJI['atm']            = '$Et';
    $EMOJI['hotel']          = '$Ex';
    $EMOJI['cvs']            = '$Ev';
    $EMOJI['gas_station']    = '$GZ';
    $EMOJI['parking']        = '$Eo';
    $EMOJI['signal']         = '$En';
    $EMOJI['toilet']         = '$Eq';
    $EMOJI['restaurant']     = '$Gc';
    $EMOJI['cafe']           = '$Ge';
    $EMOJI['bar']            = '$Gd';
    $EMOJI['beer']           = '$Gg';
    $EMOJI['first_food']     = '$E@';
    $EMOJI['boutique']       = '$E^';
    $EMOJI['beauty_salon']   = '$E?';
    $EMOJI['karaoke']        = '$G\';
    $EMOJI['movie']          = '$G]';
    $EMOJI['right_up']       = '$FV';
    $EMOJI['amusement_park'] = '$ED';
    $EMOJI['music']          = '$G\';
    $EMOJI['art']            = '$GR';
    $EMOJI['drama']          = '$E1';
    $EMOJI['event']          = '$E7';
    $EMOJI['ticket']         = '$EE';
    $EMOJI['smoking']        = '$O.';
    $EMOJI['no_smoking']     = '$F(';
    $EMOJI['camera']         = '$G(';
    $EMOJI['bag']            = '$E>';
    $EMOJI['book']           = '$Eh';
    $EMOJI['ribbon']         = '$E2';
    $EMOJI['present']        = '$E2';
    $EMOJI['birthday']       = '$Ok';
    $EMOJI['telephone']      = '$G)';
    $EMOJI['mobile']         = '$G*';
    $EMOJI['memo']           = '$Eh';
    $EMOJI['tv']             = '$EJ';
    $EMOJI['game']           = '$EK';
    $EMOJI['cd']             = '$EF';
    $EMOJI['heart']          = '$F,';
    $EMOJI['spade']          = '$F.';
    $EMOJI['diamond']        = '$F-';
    $EMOJI['clubs']          = '$F/';
    $EMOJI['eye']            = '$E4';
    $EMOJI['ear']            = '$Ea';
    $EMOJI['goo']            = '$G0';
    $EMOJI['choki']          = '$G1';
    $EMOJI['par']            = '$G2';
    $EMOJI['right_down']     = '$FX';
    $EMOJI['left_up']        = '$FW';
    $EMOJI['foot']           = '$G\'';
    $EMOJI['shoes']          = '$G\'';
    $EMOJI['glasses']        = '$E4';
    $EMOJI['wheelchair']     = '$F*';
    $EMOJI['new_moon']       = '$Gl';   //äYìñÇ∑ÇÈäGï∂éöÇ™Ç»Ç¢ÇΩÇﬂcrescent_moonÇ∆ìØÇ∂äGï∂éöÇ≈Ç∑ÅB
    $EMOJI['chip_moon']      = '$Gl';   //äYìñÇ∑ÇÈäGï∂éöÇ™Ç»Ç¢ÇΩÇﬂcrescent_moonÇ∆ìØÇ∂äGï∂éöÇ≈Ç∑ÅB
    $EMOJI['half_moon']      = '$Gl';   //äYìñÇ∑ÇÈäGï∂éöÇ™Ç»Ç¢ÇΩÇﬂcrescent_moonÇ∆ìØÇ∂äGï∂éöÇ≈Ç∑ÅB
    $EMOJI['crescent_moon']  = '$Gl';
    $EMOJI['full_moon']      = '$Gl';   //äYìñÇ∑ÇÈäGï∂éöÇ™Ç»Ç¢ÇΩÇﬂcrescent_moonÇ∆ìØÇ∂äGï∂éöÇ≈Ç∑ÅB
    $EMOJI['dog']            = '$Gr';
    $EMOJI['cat']            = '$Go';
    $EMOJI['resort']         = '$G:';
    $EMOJI['xmas']           = '$GS';
    $EMOJI['left_down']      = '$FY';
    $EMOJI['kachinko']       = '$G]';
    $EMOJI['pouch']          = '$E>';
    $EMOJI['pen']            = '$O!';
    $EMOJI['shadow']         = '$EX';
    $EMOJI['chair']          = '$E?';   //äYìñÇ∑ÇÈäGï∂éöÇ™Ç»Ç¢ÇΩÇﬂÅAê≥ämÇ…ï\ÇµÇƒÇ¢ÇÈÇ∆ÇÕÇ¢Ç¶Ç‹ÇπÇÒÅB
    $EMOJI['night']          = '$Ef';
    $EMOJI['soon']           = '$F\';   //äYìñÇ∑ÇÈäGï∂éöÇ™Ç»Ç¢ÇΩÇﬂÅAê≥ämÇ…ï\ÇµÇƒÇ¢ÇÈÇ∆ÇÕÇ¢Ç¶Ç‹ÇπÇÒÅB
    $EMOJI['on']             = '$F3';   //äYìñÇ∑ÇÈäGï∂éöÇ™Ç»Ç¢ÇΩÇﬂÅAê≥ämÇ…ï\ÇµÇƒÇ¢ÇÈÇ∆ÇÕÇ¢Ç¶Ç‹ÇπÇÒÅB
    $EMOJI['end']            = '$F]';   //äYìñÇ∑ÇÈäGï∂éöÇ™Ç»Ç¢ÇΩÇﬂÅAê≥ämÇ…ï\ÇµÇƒÇ¢ÇÈÇ∆ÇÕÇ¢Ç¶Ç‹ÇπÇÒÅB
    $EMOJI['clock']          = '$GG';
    $EMOJI['phone_to']       = '$E$';
    $EMOJI['mail_to']        = '$E#';
    $EMOJI['fax_to']         = '$G+';
    $EMOJI['carrier']        = '$Fu';    //äYìñÇ∑ÇÈäGï∂éöÇ™Ç»Ç¢ÇΩÇﬂãÛï∂éöóÒÇ…ïœä∑Ç≥ÇÍÇ‹Ç∑ÅB
    $EMOJI['carrier_2']      = '$Fu';    //äYìñÇ∑ÇÈäGï∂éöÇ™Ç»Ç¢ÇΩÇﬂãÛï∂éöóÒÇ…ïœä∑Ç≥ÇÍÇ‹Ç∑ÅB
    $EMOJI['mail']           = '$E#';
    $EMOJI['offer']          = '$Ft';    //äYìñÇ∑ÇÈäGï∂éöÇ™Ç»Ç¢ÇΩÇﬂãÛï∂éöóÒÇ…ïœä∑Ç≥ÇÍÇ‹Ç∑ÅB
    $EMOJI['point']          = '$Fu';    //äYìñÇ∑ÇÈäGï∂éöÇ™Ç»Ç¢ÇΩÇﬂãÛï∂éöóÒÇ…ïœä∑Ç≥ÇÍÇ‹Ç∑ÅB
    $EMOJI['yen']            = '$F5';
    $EMOJI['free']           = '$F6';
    $EMOJI['id']             = '$FI';
    $EMOJI['password']       = '$G_';
    $EMOJI['return']         = '$FP';
    $EMOJI['clear']          = '$F6';
    $EMOJI['search']         = '$E4';
    $EMOJI['new']            = '$F2';
    $EMOJI['place']          = '$F#';
    $EMOJI['free_dial']      = '$F1';
    $EMOJI['sharp_dial']     = '$F0';
    $EMOJI['mob_q']          = '$G*';
    $EMOJI['1']              = '$F<';
    $EMOJI['2']              = '$F=';
    $EMOJI['3']              = '$F>';
    $EMOJI['4']              = '$F?';
    $EMOJI['5']              = '$F@';
    $EMOJI['6']              = '$FA';
    $EMOJI['7']              = '$FB';
    $EMOJI['8']              = '$FC';
    $EMOJI['9']              = '$FD';
    $EMOJI['0']              = '$FE';
    $EMOJI['heart_black']    = '$GB';
    $EMOJI['heart_wave']     = '$GB';
    $EMOJI['heart_break']    = '$GC';
    $EMOJI['hearts']         = '$GB';
    $EMOJI['face_smile']     = '$Gw';
    $EMOJI['face_angry']     = '$Gy';
    $EMOJI['face_deject']    = '$Gx';
    $EMOJI['face_sad']       = '$Gx';
    $EMOJI['face_swing']     = '$E\'';
    $EMOJI['good']           = '$G.';
    $EMOJI['cheerful']       = '$G^';
    $EMOJI['feel_good']      = '$EC';
    $EMOJI['cute']           = '$F$';
    $EMOJI['kiss']           = '$G#';
    $EMOJI['shine']          = '$F9';
    $EMOJI['spark']          = '$E/';
    $EMOJI['anger']          = '$Gy';
    $EMOJI['punch']          = '$G-';
    $EMOJI['bomb']           = '$E7';
    $EMOJI['mood']           = '$G^';
    $EMOJI['bad']            = '$FY';
    $EMOJI['sleep']          = '$E\';
    $EMOJI['exc']            = '$GA';
    $EMOJI['exc_que']        = '$GA$G@';
    $EMOJI['exc_2']          = '$GA$GA';
    $EMOJI['shock']          = '$E-';
    $EMOJI['sweat']          = '$OQ';
    $EMOJI['sweat_2']        = '$E(';
    $EMOJI['dash']           = '$OP';
    $EMOJI['long_vowel']     = '$FT';
    $EMOJI['long_vowel_2']   = '$F1';
    $EMOJI['ok']             = '$Fm';
    $EMOJI['appli']          = '$Fw';    //äYìñÇ∑ÇÈäGï∂éöÇ™Ç»Ç¢ÇΩÇﬂãÛï∂éöóÒÇ…ïœä∑Ç≥ÇÍÇ‹Ç∑ÅB
    $EMOJI['appli_2']        = '$Fw';    //äYìñÇ∑ÇÈäGï∂éöÇ™Ç»Ç¢ÇΩÇﬂãÛï∂éöóÒÇ…ïœä∑Ç≥ÇÍÇ‹Ç∑ÅB
    $EMOJI['t-shirts']       = '$G&';
    $EMOJI['wallet']         = '$EO';
    $EMOJI['makeup']         = '$G#';
    $EMOJI['jeans']          = '$O9';
    $EMOJI['snow_board']     = '$G3';
    $EMOJI['chapel']         = '$GW';
    $EMOJI['door']           = '$GV';
    $EMOJI['dollar']         = '$EO';
    $EMOJI['pc']             = '$G,';
    $EMOJI['love_letter']    = '$E!';
    $EMOJI['wrench']         = '$E6';
    $EMOJI['pencil']         = '$O!';
    $EMOJI['crown']          = '$E.';
    $EMOJI['ring']           = '$GT';
    $EMOJI['sandglass']      = '$GO';
    $EMOJI['bicycle']        = '$EV';
    $EMOJI['teacup']         = '$Ge';
    $EMOJI['watch']          = '$GG';
    $EMOJI['face_think']     = '$Gx';
    $EMOJI['face_peace']     = '$Gv';
    $EMOJI['face_hurry']     = '$E(';
    $EMOJI['face_hurry_2']   = '$E(';
    $EMOJI['face_angry_2']   = '$Gy';
    $EMOJI['face_poker']     = '$Gv';
    $EMOJI['face_heart']     = '$E&';
    $EMOJI['finger']         = '$G.';
    $EMOJI['face_joke']      = '$E%';
    $EMOJI['face_wink']      = '$E%';
    $EMOJI['face_happy']     = '$Gw';
    $EMOJI['face_patience']  = '$Gx';
    $EMOJI['cat_2']          = '$Go';
    $EMOJI['face_cry']       = '$Gx';
    $EMOJI['tear']           = '$Gx';
    $EMOJI['ng']             = '$F\'';
    $EMOJI['clip']           = '$O!';
    $EMOJI['copyright']      = '$Fn';
    $EMOJI['tm']             = '$QW';
    $EMOJI['runner']         = '$E5';
    $EMOJI['secret']         = '$Ed';
    $EMOJI['recycling']      = '$ON';
    $EMOJI['regist']         = '$Fo';
    $EMOJI['warning']        = '$Fr';
    $EMOJI['prohibition']    = '$F\'';
    $EMOJI['empty']          = '$FK';
    $EMOJI['success']        = '$G.';
    $EMOJI['full']           = '$FJ';
    $EMOJI['right_left']     = '$FU$FT';
    $EMOJI['up_down']        = '$FR$FS';
    $EMOJI['school']         = '$Ew';
    $EMOJI['wave']           = '$G7';
    $EMOJI['mountain']       = '$G[';
    $EMOJI['clover']         = '$E0';
    $EMOJI['cherry']         = '$Og';
    $EMOJI['tulip']          = '$O$';
    $EMOJI['banana']         = '$Of';
    $EMOJI['apple']          = '$Oe';
    $EMOJI['leaf']           = '$E0';
    $EMOJI['maple']          = '$E8';
    $EMOJI['cherry_blossom'] = '$GP';
    $EMOJI['rice_ball']      = '$Ob';
    $EMOJI['cake']           = '$Gf';
    $EMOJI['sake']           = '$O+';
    $EMOJI['bowl']           = '$OX';
    $EMOJI['pan']            = '$OY';
    $EMOJI['snail']          = '$QQ';
    $EMOJI['baby_bird']      = '$QC';
    $EMOJI['penguin']        = '$Gu';
    $EMOJI['fish']           = '$G9';
    $EMOJI['face_delicious'] = '$Gv';
    $EMOJI['face_foppish']   = '$Gw';
    $EMOJI['horse']          = '$G:';
    $EMOJI['pig']            = '$E+';
    $EMOJI['wine']           = '$Gd';
    $EMOJI['face_let_down']  = '$E\'';

} elseif ( $CARRIER_ID === 'e' ) {
    if(!$hdml_flg){
        $EMOJI['sun'] = '<img localsrc="44">'; 
        $EMOJI['cloud'] = '<img localsrc="107">'; 
        $EMOJI['rain'] = '<img localsrc="95">'; 
        $EMOJI['snow'] = '<img localsrc="191">'; 
        $EMOJI['thunder'] = '<img localsrc="16">'; 
        $EMOJI['typhoon'] = '<img localsrc="190">'; 
        $EMOJI['fog'] = '<img localsrc="305">'; 
        $EMOJI['light_rain'] = '<img localsrc="481">'; 
        $EMOJI['ram'] = '<img localsrc="192">'; 
        $EMOJI['bull'] = '<img localsrc="193">'; 
        $EMOJI['twins'] = '<img localsrc="194">'; 
        $EMOJI['crab'] = '<img localsrc="195">'; 
        $EMOJI['lion'] = '<img localsrc="196">'; 
        $EMOJI['virgin'] = '<img localsrc="197">'; 
        $EMOJI['balance'] = '<img localsrc="198">'; 
        $EMOJI['scorpion'] = '<img localsrc="199">'; 
        $EMOJI['archer'] = '<img localsrc="200">'; 
        $EMOJI['goat'] = '<img localsrc="201">'; 
        $EMOJI['water_bearer'] = '<img localsrc="202">'; 
        $EMOJI['fishes'] = '<img localsrc="203">'; 
        $EMOJI['sports'] = '<img localsrc="218">'; 
        $EMOJI['baseball'] = '<img localsrc="45">'; 
        $EMOJI['golf'] = '<img localsrc="306">'; 
        $EMOJI['tennis'] = '<img localsrc="220">'; 
        $EMOJI['soccer'] = '<img localsrc="219">'; 
        $EMOJI['ski'] = '<img localsrc="421">'; 
        $EMOJI['basketball'] = '<img localsrc="307">'; 
        $EMOJI['flag'] = '<img localsrc="222">'; 
        $EMOJI['pocket_bell'] = '<img localsrc="308">'; 
        $EMOJI['train'] = '<img localsrc="172">'; 
        $EMOJI['subway'] = '<img localsrc="341">'; 
        $EMOJI['shinkansen'] = '<img localsrc="217">'; 
        $EMOJI['car'] = '<img localsrc="125">'; 
        $EMOJI['car_2'] = '<img localsrc="125">'; 
        $EMOJI['bus'] = '<img localsrc="216">'; 
        $EMOJI['ship'] = '<img localsrc="379">'; 
        $EMOJI['airplane'] = '<img localsrc="168">'; 
        $EMOJI['house'] = '<img localsrc="112">'; 
        $EMOJI['building'] = '<img localsrc="156">'; 
        $EMOJI['post_office'] = '<img localsrc="375">'; 
        $EMOJI['hospital'] = '<img localsrc="376">'; 
        $EMOJI['bank'] = '<img localsrc="212">'; 
        $EMOJI['atm'] = '<img localsrc="205">'; 
        $EMOJI['hotel'] = '<img localsrc="378">'; 
        $EMOJI['cvs'] = '<img localsrc="206">'; 
        $EMOJI['gas_station'] = '<img localsrc="213">'; 
        $EMOJI['parking'] = '<img localsrc="208">'; 
        $EMOJI['signal'] = '<img localsrc="99">'; 
        $EMOJI['toilet'] = '<img localsrc="207">'; 
        $EMOJI['restaurant'] = '<img localsrc="146">'; 
        $EMOJI['cafe'] = '<img localsrc="93">'; 
        $EMOJI['bar'] = '<img localsrc="52">'; 
        $EMOJI['beer'] = '<img localsrc="65">'; 
        $EMOJI['first_food'] = '<img localsrc="245">'; 
        $EMOJI['boutique'] = '<img localsrc="124">'; 
        $EMOJI['beauty_salon'] = '<img localsrc="104">'; 
        $EMOJI['karaoke'] = '<img localsrc="289">'; 
        $EMOJI['movie'] = '<img localsrc="110">'; 
        $EMOJI['right_up'] = '<img localsrc="70">'; 
        $EMOJI['amusement_park'] = '<img localsrc="223">'; 
        $EMOJI['music'] = '<img localsrc="294">'; 
        $EMOJI['art'] = '<img localsrc="309">'; 
        $EMOJI['drama'] = '<img localsrc="310">'; 
        $EMOJI['event'] = '<img localsrc="311">'; 
        $EMOJI['ticket'] = '<img localsrc="106">'; 
        $EMOJI['smoking'] = '<img localsrc="176">'; 
        $EMOJI['no_smoking'] = '<img localsrc="177">'; 
        $EMOJI['camera'] = '<img localsrc="94">'; 
        $EMOJI['bag'] = '<img localsrc="83">'; 
        $EMOJI['book'] = '<img localsrc="122">'; 
        $EMOJI['ribbon'] = '<img localsrc="312">'; 
        $EMOJI['present'] = '<img localsrc="144">'; 
        $EMOJI['birthday'] = '<img localsrc="313">'; 
        $EMOJI['telephone'] = '<img localsrc="85">'; 
        $EMOJI['mobile'] = '<img localsrc="161">'; 
        $EMOJI['memo'] = '<img localsrc="56">'; 
        $EMOJI['tv'] = '<img localsrc="288">'; 
        $EMOJI['game'] = '<img localsrc="232">'; 
        $EMOJI['cd'] = '<img localsrc="300">'; 
        $EMOJI['heart'] = '<img localsrc="414">'; 
        $EMOJI['spade'] = '<img localsrc="314">'; 
        $EMOJI['diamond'] = '<img localsrc="315">'; 
        $EMOJI['clubs'] = '<img localsrc="316">'; 
        $EMOJI['eye'] = '<img localsrc="317">'; 
        $EMOJI['ear'] = '<img localsrc="318">'; 
        $EMOJI['goo'] = '<img localsrc="817">'; 
        $EMOJI['choki'] = '<img localsrc="319">'; 
        $EMOJI['par'] = '<img localsrc="320">'; 
        $EMOJI['right_down'] = '<img localsrc="43">'; 
        $EMOJI['left_up'] = '<img localsrc="42">'; 
        $EMOJI['foot'] = '<img localsrc="728">'; 
        $EMOJI['shoes'] = '<img localsrc="729">'; 
        $EMOJI['glasses'] = '<img localsrc="116">'; 
        $EMOJI['wheelchair'] = '<img localsrc="178">'; 
        $EMOJI['new_moon'] = '<img localsrc="321">'; 
        $EMOJI['chip_moon'] = '<img localsrc="322">'; 
        $EMOJI['half_moon'] = '<img localsrc="323">'; 
        $EMOJI['crescent_moon'] = '<img localsrc="15">'; 
        $EMOJI['full_moon'] = '<img localsrc="47">'; 
        $EMOJI['dog'] = '<img localsrc="134">'; 
        $EMOJI['cat'] = '<img localsrc="251">'; 
        $EMOJI['resort'] = '<img localsrc="169">'; 
        $EMOJI['xmas'] = '<img localsrc="234">'; 
        $EMOJI['left_down'] = '<img localsrc="71">'; 
        $EMOJI['kachinko'] = '<img localsrc="226">'; 
        $EMOJI['pouch'] = '<img localsrc="233">'; 
        $EMOJI['pen'] = '<img localsrc="508">'; 
        $EMOJI['shadow'] = '<img localsrc="80">'; 
        $EMOJI['chair'] = ''; 
        $EMOJI['night'] = '<img localsrc="227">'; 
        $EMOJI['soon'] = '<img localsrc="63">'; 
        $EMOJI['on'] = '<img localsrc="808">'; 
        $EMOJI['end'] = '<img localsrc="64">'; 
        $EMOJI['clock'] = '<img localsrc="46">'; 
        $EMOJI['phone_to'] = '<img localsrc="513">'; 
        $EMOJI['mail_to'] = '<img localsrc="784">'; 
        $EMOJI['fax_to'] = '<img localsrc="166">'; 
        $EMOJI['carrier'] = 'i'; 
        $EMOJI['carrier_2'] = 'i'; 
        $EMOJI['mail'] = '<img localsrc="108">'; 
        $EMOJI['offer'] = 'D'; 
        $EMOJI['point'] = 'D'; 
        $EMOJI['yen'] = '<img localsrc="109">'; 
        $EMOJI['free'] = '<img localsrc="299">'; 
        $EMOJI['id'] = '<img localsrc="385">'; 
        $EMOJI['password'] = '<img localsrc="120">'; 
        $EMOJI['return'] = '<img localsrc="118">'; 
        $EMOJI['clear'] = '<img localsrc="324">'; 
        $EMOJI['search'] = '<img localsrc="119">'; 
        $EMOJI['new'] = '<img localsrc="334">'; 
        $EMOJI['place'] = '<img localsrc="730">'; 
        $EMOJI['free_dial'] = 'F'; 
        $EMOJI['sharp_dial'] = '#'; 
        $EMOJI['mob_q'] = 'Q'; 
        $EMOJI['1'] = '<img localsrc="180">'; 
        $EMOJI['2'] = '<img localsrc="181">'; 
        $EMOJI['3'] = '<img localsrc="182">'; 
        $EMOJI['4'] = '<img localsrc="183">'; 
        $EMOJI['5'] = '<img localsrc="184">'; 
        $EMOJI['6'] = '<img localsrc="185">'; 
        $EMOJI['7'] = '<img localsrc="186">'; 
        $EMOJI['8'] = '<img localsrc="187">'; 
        $EMOJI['9'] = '<img localsrc="188">'; 
        $EMOJI['0'] = '<img localsrc="325">'; 
        $EMOJI['heart_black'] = '<img localsrc="51">'; 
        $EMOJI['heart_wave'] = '<img localsrc="328">'; 
        $EMOJI['heart_break'] = '<img localsrc="265">'; 
        $EMOJI['hearts'] = '<img localsrc="266">'; 
        $EMOJI['face_smile'] = '<img localsrc="257">'; 
        $EMOJI['face_angry'] = '<img localsrc="258">'; 
        $EMOJI['face_deject'] = '<img localsrc="260">'; 
        $EMOJI['face_sad'] = '<img localsrc="259">'; 
        $EMOJI['face_swing'] = '<img localsrc="327">'; 
        $EMOJI['good'] = '<img localsrc="731">'; 
        $EMOJI['cheerful'] = '<img localsrc="343">'; 
        $EMOJI['feel_good'] = '<img localsrc="224">'; 
        $EMOJI['cute'] = '<img localsrc="19">'; 
        $EMOJI['kiss'] = '<img localsrc="273">'; 
        $EMOJI['shine'] = '<img localsrc="420">'; 
        $EMOJI['spark'] = '<img localsrc="77">'; 
        $EMOJI['anger'] = '<img localsrc="262">'; 
        $EMOJI['punch'] = '<img localsrc="281">'; 
        $EMOJI['bomb'] = '<img localsrc="268">'; 
        $EMOJI['mood'] = '<img localsrc="291">'; 
        $EMOJI['bad'] = '<img localsrc="732">'; 
        $EMOJI['sleep'] = '<img localsrc="261">'; 
        $EMOJI['exc'] = '<img localsrc="2">'; 
        $EMOJI['exc_que'] = '<img localsrc="733">'; 
        $EMOJI['exc_2'] = '<img localsrc="734">'; 
        $EMOJI['shock'] = '<img localsrc="329">'; 
        $EMOJI['sweat'] = '<img localsrc="330">'; 
        $EMOJI['sweat_2'] = '<img localsrc="263">'; 
        $EMOJI['dash'] = '<img localsrc="282">'; 
        $EMOJI['long_vowel'] = '<img localsrc="810">'; 
        $EMOJI['long_vowel_2'] = '<img localsrc="735">'; 
        $EMOJI['ok'] = '<img localsrc="326">'; 
        $EMOJI['appli'] = 'Éø'; 
        $EMOJI['appli_2'] = 'Éø'; 
        $EMOJI['t-shirts'] = '<img localsrc="335">'; 
        $EMOJI['wallet'] = '<img localsrc="290">'; 
        $EMOJI['makeup'] = '<img localsrc="295">'; 
        $EMOJI['jeans'] = '<img localsrc="805">'; 
        $EMOJI['snow_board'] = '<img localsrc="221">'; 
        $EMOJI['chapel'] = '<img localsrc="48">'; 
        $EMOJI['door'] = ''; 
        $EMOJI['dollar'] = '<img localsrc="233">'; 
        $EMOJI['pc'] = '<img localsrc="337">'; 
        $EMOJI['love_letter'] = '<img localsrc="806">'; 
        $EMOJI['wrench'] = '<img localsrc="152">'; 
        $EMOJI['pencil'] = '<img localsrc="149">'; 
        $EMOJI['crown'] = '<img localsrc="354">'; 
        $EMOJI['ring'] = '<img localsrc="72">'; 
        $EMOJI['sandglass'] = '<img localsrc="58">'; 
        $EMOJI['bicycle'] = '<img localsrc="215">'; 
        $EMOJI['teacup'] = '<img localsrc="423">'; 
        $EMOJI['watch'] = '<img localsrc="25">'; 
        $EMOJI['face_think'] = '<img localsrc="443">'; 
        $EMOJI['face_peace'] = '<img localsrc="454">'; 
        $EMOJI['face_hurry'] = '<img localsrc="351">'; 
        $EMOJI['face_hurry_2'] = '<img localsrc="351">'; 
        $EMOJI['face_angry_2'] = '<img localsrc="779">'; 
        $EMOJI['face_poker'] = '<img localsrc="789">'; 
        $EMOJI['face_heart'] = '<img localsrc="349">'; 
        $EMOJI['finger'] = '<img localsrc="287">'; 
        $EMOJI['face_joke'] = '<img localsrc="264">'; 
        $EMOJI['face_wink'] = '<img localsrc="348">'; 
        $EMOJI['face_happy'] = '<img localsrc="257">'; 
        $EMOJI['face_patience'] = '<img localsrc="260">'; 
        $EMOJI['cat_2'] = '<img localsrc="783">'; 
        $EMOJI['face_cry'] = '<img localsrc="259">'; 
        $EMOJI['tear'] = '<img localsrc="791">'; 
        $EMOJI['ng'] = ''; 
        $EMOJI['clip'] = '<img localsrc="143">'; 
        $EMOJI['copyright'] = '<img localsrc="81">'; 
        $EMOJI['tm'] = '<img localsrc="54">'; 
        $EMOJI['runner'] = '<img localsrc="218">'; 
        $EMOJI['secret'] = '<img localsrc="279">'; 
        $EMOJI['recycling'] = '<img localsrc="807">'; 
        $EMOJI['regist'] = '<img localsrc="82">'; 
        $EMOJI['warning'] = '<img localsrc="1">'; 
        $EMOJI['prohibition'] = 'ã÷'; 
        $EMOJI['empty'] = '<img localsrc="387">'; 
        $EMOJI['success'] = 'çá'; 
        $EMOJI['full'] = '<img localsrc="386">'; 
        $EMOJI['right_left'] = '<img localsrc="808">'; 
        $EMOJI['up_down'] = '<img localsrc="809">'; 
        $EMOJI['school'] = '<img localsrc="377">'; 
        $EMOJI['wave'] = '<img localsrc="810">'; 
        $EMOJI['mountain'] = '<img localsrc="342">'; 
        $EMOJI['clover'] = '<img localsrc="53">'; 
        $EMOJI['cherry'] = '<img localsrc="241">'; 
        $EMOJI['tulip'] = '<img localsrc="113">'; 
        $EMOJI['banana'] = '<img localsrc="739">'; 
        $EMOJI['apple'] = '<img localsrc="434">'; 
        $EMOJI['leaf'] = '<img localsrc="811">'; 
        $EMOJI['maple'] = '<img localsrc="133">'; 
        $EMOJI['cherry_blossom'] = '<img localsrc="235">'; 
        $EMOJI['rice_ball'] = '<img localsrc="244">'; 
        $EMOJI['cake'] = '<img localsrc="239">'; 
        $EMOJI['sake'] = '<img localsrc="400">'; 
        $EMOJI['bowl'] = '<img localsrc="429">'; 
        $EMOJI['pan'] = '<img localsrc="424">'; 
        $EMOJI['snail'] = '<img localsrc="812">'; 
        $EMOJI['baby_bird'] = '<img localsrc="78">'; 
        $EMOJI['penguin'] = '<img localsrc="252">'; 
        $EMOJI['fish'] = '<img localsrc="203">'; 
        $EMOJI['face_delicious'] = '<img localsrc="454">'; 
        $EMOJI['face_foppish'] = '<img localsrc="814">'; 
        $EMOJI['horse'] = '<img localsrc="248">'; 
        $EMOJI['pig'] = '<img localsrc="758">'; 
        $EMOJI['wine'] = '<img localsrc="12">'; 
        $EMOJI['face_let_down'] = '<img localsrc="350">'; 
    }else{
        $EMOJI['sun'] = '<img icon="44">'; 
        $EMOJI['cloud'] = '<img icon="107">'; 
        $EMOJI['rain'] = '<img icon="95">'; 
        $EMOJI['snow'] = '<img icon="191">'; 
        $EMOJI['thunder'] = '<img icon="16">'; 
        $EMOJI['typhoon'] = '<img icon="190">'; 
        $EMOJI['fog'] = '<img icon="305">'; 
        $EMOJI['light_rain'] = '<img icon="481">'; 
        $EMOJI['ram'] = '<img icon="192">'; 
        $EMOJI['bull'] = '<img icon="193">'; 
        $EMOJI['twins'] = '<img icon="194">'; 
        $EMOJI['crab'] = '<img icon="195">'; 
        $EMOJI['lion'] = '<img icon="196">'; 
        $EMOJI['virgin'] = '<img icon="197">'; 
        $EMOJI['balance'] = '<img icon="198">'; 
        $EMOJI['scorpion'] = '<img icon="199">'; 
        $EMOJI['archer'] = '<img icon="200">'; 
        $EMOJI['goat'] = '<img icon="201">'; 
        $EMOJI['water_bearer'] = '<img icon="202">'; 
        $EMOJI['fishes'] = '<img icon="203">'; 
        $EMOJI['sports'] = '<img icon="218">'; 
        $EMOJI['baseball'] = '<img icon="45">'; 
        $EMOJI['golf'] = '<img icon="306">'; 
        $EMOJI['tennis'] = '<img icon="220">'; 
        $EMOJI['soccer'] = '<img icon="219">'; 
        $EMOJI['ski'] = '<img icon="421">'; 
        $EMOJI['basketball'] = '<img icon="307">'; 
        $EMOJI['flag'] = '<img icon="222">'; 
        $EMOJI['pocket_bell'] = '<img icon="308">'; 
        $EMOJI['train'] = '<img icon="172">'; 
        $EMOJI['subway'] = '<img icon="341">'; 
        $EMOJI['shinkansen'] = '<img icon="217">'; 
        $EMOJI['car'] = '<img icon="125">'; 
        $EMOJI['car_2'] = '<img icon="125">'; 
        $EMOJI['bus'] = '<img icon="216">'; 
        $EMOJI['ship'] = '<img icon="379">'; 
        $EMOJI['airplane'] = '<img icon="168">'; 
        $EMOJI['house'] = '<img icon="112">'; 
        $EMOJI['building'] = '<img icon="156">'; 
        $EMOJI['post_office'] = '<img icon="375">'; 
        $EMOJI['hospital'] = '<img icon="376">'; 
        $EMOJI['bank'] = '<img icon="212">'; 
        $EMOJI['atm'] = '<img icon="205">'; 
        $EMOJI['hotel'] = '<img icon="378">'; 
        $EMOJI['cvs'] = '<img icon="206">'; 
        $EMOJI['gas_station'] = '<img icon="213">'; 
        $EMOJI['parking'] = '<img icon="208">'; 
        $EMOJI['signal'] = '<img icon="99">'; 
        $EMOJI['toilet'] = '<img icon="207">'; 
        $EMOJI['restaurant'] = '<img icon="146">'; 
        $EMOJI['cafe'] = '<img icon="93">'; 
        $EMOJI['bar'] = '<img icon="52">'; 
        $EMOJI['beer'] = '<img icon="65">'; 
        $EMOJI['first_food'] = '<img icon="245">'; 
        $EMOJI['boutique'] = '<img icon="124">'; 
        $EMOJI['beauty_salon'] = '<img icon="104">'; 
        $EMOJI['karaoke'] = '<img icon="289">'; 
        $EMOJI['movie'] = '<img icon="110">'; 
        $EMOJI['right_up'] = '<img icon="70">'; 
        $EMOJI['amusement_park'] = '<img icon="223">'; 
        $EMOJI['music'] = '<img icon="294">'; 
        $EMOJI['art'] = '<img icon="309">'; 
        $EMOJI['drama'] = '<img icon="310">'; 
        $EMOJI['event'] = '<img icon="311">'; 
        $EMOJI['ticket'] = '<img icon="106">'; 
        $EMOJI['smoking'] = '<img icon="176">'; 
        $EMOJI['no_smoking'] = '<img icon="177">'; 
        $EMOJI['camera'] = '<img icon="94">'; 
        $EMOJI['bag'] = '<img icon="83">'; 
        $EMOJI['book'] = '<img icon="122">'; 
        $EMOJI['ribbon'] = '<img icon="312">'; 
        $EMOJI['present'] = '<img icon="144">'; 
        $EMOJI['birthday'] = '<img icon="313">'; 
        $EMOJI['telephone'] = '<img icon="85">'; 
        $EMOJI['mobile'] = '<img icon="161">'; 
        $EMOJI['memo'] = '<img icon="56">'; 
        $EMOJI['tv'] = '<img icon="288">'; 
        $EMOJI['game'] = '<img icon="232">'; 
        $EMOJI['cd'] = '<img icon="300">'; 
        $EMOJI['heart'] = '<img icon="414">'; 
        $EMOJI['spade'] = '<img icon="314">'; 
        $EMOJI['diamond'] = '<img icon="315">'; 
        $EMOJI['clubs'] = '<img icon="316">'; 
        $EMOJI['eye'] = '<img icon="317">'; 
        $EMOJI['ear'] = '<img icon="318">'; 
        $EMOJI['goo'] = '<img icon="817">'; 
        $EMOJI['choki'] = '<img icon="319">'; 
        $EMOJI['par'] = '<img icon="320">'; 
        $EMOJI['right_down'] = '<img icon="43">'; 
        $EMOJI['left_up'] = '<img icon="42">'; 
        $EMOJI['foot'] = '<img icon="728">'; 
        $EMOJI['shoes'] = '<img icon="729">'; 
        $EMOJI['glasses'] = '<img icon="116">'; 
        $EMOJI['wheelchair'] = '<img icon="178">'; 
        $EMOJI['new_moon'] = '<img icon="321">'; 
        $EMOJI['chip_moon'] = '<img icon="322">'; 
        $EMOJI['half_moon'] = '<img icon="323">'; 
        $EMOJI['crescent_moon'] = '<img icon="15">'; 
        $EMOJI['full_moon'] = '<img icon="47">'; 
        $EMOJI['dog'] = '<img icon="134">'; 
        $EMOJI['cat'] = '<img icon="251">'; 
        $EMOJI['resort'] = '<img icon="169">'; 
        $EMOJI['xmas'] = '<img icon="234">'; 
        $EMOJI['left_down'] = '<img icon="71">'; 
        $EMOJI['kachinko'] = '<img icon="226">'; 
        $EMOJI['pouch'] = '<img icon="233">'; 
        $EMOJI['pen'] = '<img icon="508">'; 
        $EMOJI['shadow'] = '<img icon="80">'; 
        $EMOJI['chair'] = ''; 
        $EMOJI['night'] = '<img icon="227">'; 
        $EMOJI['soon'] = '<img icon="63">'; 
        $EMOJI['on'] = '<img icon="808">'; 
        $EMOJI['end'] = '<img icon="64">'; 
        $EMOJI['clock'] = '<img icon="46">'; 
        $EMOJI['phone_to'] = '<img icon="513">'; 
        $EMOJI['mail_to'] = '<img icon="784">'; 
        $EMOJI['fax_to'] = '<img icon="166">'; 
        $EMOJI['carrier'] = 'i'; 
        $EMOJI['carrier_2'] = 'i'; 
        $EMOJI['mail'] = '<img icon="108">'; 
        $EMOJI['offer'] = 'D'; 
        $EMOJI['point'] = 'D'; 
        $EMOJI['yen'] = '<img icon="109">'; 
        $EMOJI['free'] = '<img icon="299">'; 
        $EMOJI['id'] = '<img icon="385">'; 
        $EMOJI['password'] = '<img icon="120">'; 
        $EMOJI['return'] = '<img icon="118">'; 
        $EMOJI['clear'] = '<img icon="324">'; 
        $EMOJI['search'] = '<img icon="119">'; 
        $EMOJI['new'] = '<img icon="334">'; 
        $EMOJI['place'] = '<img icon="730">'; 
        $EMOJI['free_dial'] = 'F'; 
        $EMOJI['sharp_dial'] = '#'; 
        $EMOJI['mob_q'] = 'Q'; 
        $EMOJI['1'] = '<img icon="180">'; 
        $EMOJI['2'] = '<img icon="181">'; 
        $EMOJI['3'] = '<img icon="182">'; 
        $EMOJI['4'] = '<img icon="183">'; 
        $EMOJI['5'] = '<img icon="184">'; 
        $EMOJI['6'] = '<img icon="185">'; 
        $EMOJI['7'] = '<img icon="186">'; 
        $EMOJI['8'] = '<img icon="187">'; 
        $EMOJI['9'] = '<img icon="188">'; 
        $EMOJI['0'] = '<img icon="325">'; 
        $EMOJI['heart_black'] = '<img icon="51">'; 
        $EMOJI['heart_wave'] = '<img icon="328">'; 
        $EMOJI['heart_break'] = '<img icon="265">'; 
        $EMOJI['hearts'] = '<img icon="266">'; 
        $EMOJI['face_smile'] = '<img icon="257">'; 
        $EMOJI['face_angry'] = '<img icon="258">'; 
        $EMOJI['face_deject'] = '<img icon="260">'; 
        $EMOJI['face_sad'] = '<img icon="259">'; 
        $EMOJI['face_swing'] = '<img icon="327">'; 
        $EMOJI['good'] = '<img icon="731">'; 
        $EMOJI['cheerful'] = '<img icon="343">'; 
        $EMOJI['feel_good'] = '<img icon="224">'; 
        $EMOJI['cute'] = '<img icon="19">'; 
        $EMOJI['kiss'] = '<img icon="273">'; 
        $EMOJI['shine'] = '<img icon="420">'; 
        $EMOJI['spark'] = '<img icon="77">'; 
        $EMOJI['anger'] = '<img icon="262">'; 
        $EMOJI['punch'] = '<img icon="281">'; 
        $EMOJI['bomb'] = '<img icon="268">'; 
        $EMOJI['mood'] = '<img icon="291">'; 
        $EMOJI['bad'] = '<img icon="732">'; 
        $EMOJI['sleep'] = '<img icon="261">'; 
        $EMOJI['exc'] = '<img icon="2">'; 
        $EMOJI['exc_que'] = '<img icon="733">'; 
        $EMOJI['exc_2'] = '<img icon="734">'; 
        $EMOJI['shock'] = '<img icon="329">'; 
        $EMOJI['sweat'] = '<img icon="330">'; 
        $EMOJI['sweat_2'] = '<img icon="263">'; 
        $EMOJI['dash'] = '<img icon="282">'; 
        $EMOJI['long_vowel'] = '<img icon="810">'; 
        $EMOJI['long_vowel_2'] = '<img icon="735">'; 
        $EMOJI['ok'] = '<img icon="326">'; 
        $EMOJI['appli'] = 'Éø'; 
        $EMOJI['appli_2'] = 'Éø'; 
        $EMOJI['t-shirts'] = '<img icon="335">'; 
        $EMOJI['wallet'] = '<img icon="290">'; 
        $EMOJI['makeup'] = '<img icon="295">'; 
        $EMOJI['jeans'] = '<img icon="805">'; 
        $EMOJI['snow_board'] = '<img icon="221">'; 
        $EMOJI['chapel'] = '<img icon="48">'; 
        $EMOJI['door'] = ''; 
        $EMOJI['dollar'] = '<img icon="233">'; 
        $EMOJI['pc'] = '<img icon="337">'; 
        $EMOJI['love_letter'] = '<img icon="806">'; 
        $EMOJI['wrench'] = '<img icon="152">'; 
        $EMOJI['pencil'] = '<img icon="149">'; 
        $EMOJI['crown'] = '<img icon="354">'; 
        $EMOJI['ring'] = '<img icon="72">'; 
        $EMOJI['sandglass'] = '<img icon="58">'; 
        $EMOJI['bicycle'] = '<img icon="215">'; 
        $EMOJI['teacup'] = '<img icon="423">'; 
        $EMOJI['watch'] = '<img icon="25">'; 
        $EMOJI['face_think'] = '<img icon="443">'; 
        $EMOJI['face_peace'] = '<img icon="454">'; 
        $EMOJI['face_hurry'] = '<img icon="351">'; 
        $EMOJI['face_hurry_2'] = '<img icon="351">'; 
        $EMOJI['face_angry_2'] = '<img icon="779">'; 
        $EMOJI['face_poker'] = '<img icon="789">'; 
        $EMOJI['face_heart'] = '<img icon="349">'; 
        $EMOJI['finger'] = '<img icon="287">'; 
        $EMOJI['face_joke'] = '<img icon="264">'; 
        $EMOJI['face_wink'] = '<img icon="348">'; 
        $EMOJI['face_happy'] = '<img icon="257">'; 
        $EMOJI['face_patience'] = '<img icon="260">'; 
        $EMOJI['cat_2'] = '<img icon="783">'; 
        $EMOJI['face_cry'] = '<img icon="259">'; 
        $EMOJI['tear'] = '<img icon="791">'; 
        $EMOJI['ng'] = ''; 
        $EMOJI['clip'] = '<img icon="143">'; 
        $EMOJI['copyright'] = '<img icon="81">'; 
        $EMOJI['tm'] = '<img icon="54">'; 
        $EMOJI['runner'] = '<img icon="218">'; 
        $EMOJI['secret'] = '<img icon="279">'; 
        $EMOJI['recycling'] = '<img icon="807">'; 
        $EMOJI['regist'] = '<img icon="82">'; 
        $EMOJI['warning'] = '<img icon="1">'; 
        $EMOJI['prohibition'] = 'ã÷'; 
        $EMOJI['empty'] = '<img icon="387">'; 
        $EMOJI['success'] = 'çá'; 
        $EMOJI['full'] = '<img icon="386">'; 
        $EMOJI['right_left'] = '<img icon="808">'; 
        $EMOJI['up_down'] = '<img icon="809">'; 
        $EMOJI['school'] = '<img icon="377">'; 
        $EMOJI['wave'] = '<img icon="810">'; 
        $EMOJI['mountain'] = '<img icon="342">'; 
        $EMOJI['clover'] = '<img icon="53">'; 
        $EMOJI['cherry'] = '<img icon="241">'; 
        $EMOJI['tulip'] = '<img icon="113">'; 
        $EMOJI['banana'] = '<img icon="739">'; 
        $EMOJI['apple'] = '<img icon="434">'; 
        $EMOJI['leaf'] = '<img icon="811">'; 
        $EMOJI['maple'] = '<img icon="133">'; 
        $EMOJI['cherry_blossom'] = '<img icon="235">'; 
        $EMOJI['rice_ball'] = '<img icon="244">'; 
        $EMOJI['cake'] = '<img icon="239">'; 
        $EMOJI['sake'] = '<img icon="400">'; 
        $EMOJI['bowl'] = '<img icon="429">'; 
        $EMOJI['pan'] = '<img icon="424">'; 
        $EMOJI['snail'] = '<img icon="812">'; 
        $EMOJI['baby_bird'] = '<img icon="78">'; 
        $EMOJI['penguin'] = '<img icon="252">'; 
        $EMOJI['fish'] = '<img icon="203">'; 
        $EMOJI['face_delicious'] = '<img icon="454">'; 
        $EMOJI['face_foppish'] = '<img icon="814">'; 
        $EMOJI['horse'] = '<img icon="248">'; 
        $EMOJI['pig'] = '<img icon="758">'; 
        $EMOJI['wine'] = '<img icon="12">'; 
        $EMOJI['face_let_down'] = '<img icon="350">'; 
    }

} elseif ( $CARRIER_ID === 'w' ) {
    //willcom
    $EMOJI['sun']            = '¯ü';
    $EMOJI['cloud']          = '¯†';
    $EMOJI['rain']           = '¯°';
    $EMOJI['snow']           = '¯¢';
    $EMOJI['thunder']        = '¯£';
    $EMOJI['typhoon']        = '¯§';
    $EMOJI['fog']            = '¯•';
    $EMOJI['light_rain']     = '¯¶';
    $EMOJI['ram']            = '¯ß';
    $EMOJI['bull']           = '¯®';
    $EMOJI['twins']          = '¯©';
    $EMOJI['crab']           = '¯™';
    $EMOJI['lion']           = '¯´';
    $EMOJI['virgin']         = '¯¨';
    $EMOJI['balance']        = '¯≠';
    $EMOJI['scorpion']       = '¯Æ';
    $EMOJI['archer']         = '¯Ø';
    $EMOJI['goat']           = '¯∞';
    $EMOJI['water_bearer']   = '¯±';
    $EMOJI['fishes']         = '¯≤';
    $EMOJI['sports']         = '¯≥';
    $EMOJI['baseball']       = '¯¥';
    $EMOJI['golf']           = '¯µ';
    $EMOJI['tennis']         = '¯∂';
    $EMOJI['soccer']         = '¯∑';
    $EMOJI['ski']            = '¯∏';
    $EMOJI['basketball']     = '¯π';
    $EMOJI['flag']           = '¯∫';
    $EMOJI['pocket_bell']    = '¯ª';
    $EMOJI['train']          = '¯º';
    $EMOJI['subway']         = '¯Ω';
    $EMOJI['shinkansen']     = '¯æ';
    $EMOJI['car']            = '¯ø';
    $EMOJI['car_2']          = '¯¿';
    $EMOJI['bus']            = '¯¡';
    $EMOJI['ship']           = '¯¬';
    $EMOJI['airplane']       = '¯√';
    $EMOJI['house']          = '¯ƒ';
    $EMOJI['building']       = '¯≈';
    $EMOJI['post_office']    = '¯∆';
    $EMOJI['hospital']       = '¯«';
    $EMOJI['bank']           = '¯»';
    $EMOJI['atm']            = '¯…';
    $EMOJI['hotel']          = '¯ ';
    $EMOJI['cvs']            = '¯À';
    $EMOJI['gas_station']    = '¯Ã';
    $EMOJI['parking']        = '¯Õ';
    $EMOJI['signal']         = '¯Œ';
    $EMOJI['toilet']         = '¯œ';
    $EMOJI['restaurant']     = '¯–';
    $EMOJI['cafe']           = '¯—';
    $EMOJI['bar']            = '¯“';
    $EMOJI['beer']           = '¯”';
    $EMOJI['first_food']     = '¯‘';
    $EMOJI['boutique']       = '¯’';
    $EMOJI['beauty_salon']   = '¯÷';
    $EMOJI['karaoke']        = '¯◊';
    $EMOJI['movie']          = '¯ÿ';
    $EMOJI['right_up']       = '¯Ÿ';
    $EMOJI['amusement_park'] = '¯⁄';
    $EMOJI['music']          = '¯€';
    $EMOJI['art']            = '¯‹';
    $EMOJI['drama']          = '¯›';
    $EMOJI['event']          = '¯ﬁ';
    $EMOJI['ticket']         = '¯ﬂ';
    $EMOJI['smoking']        = '¯‡';
    $EMOJI['no_smoking']     = '¯·';
    $EMOJI['camera']         = '¯‚';
    $EMOJI['bag']            = '¯„';
    $EMOJI['book']           = '¯‰';
    $EMOJI['ribbon']         = '¯Â';
    $EMOJI['present']        = '¯Ê';
    $EMOJI['birthday']       = '¯Á';
    $EMOJI['telephone']      = '¯Ë';
    $EMOJI['mobile']         = '¯È';
    $EMOJI['memo']           = '¯Í';
    $EMOJI['tv']             = '¯Î';
    $EMOJI['game']           = '¯Ï';
    $EMOJI['cd']             = '¯Ì';
    $EMOJI['heart']          = '¯Ó';
    $EMOJI['spade']          = '¯Ô';
    $EMOJI['diamond']        = '¯';
    $EMOJI['clubs']          = '¯Ò';
    $EMOJI['eye']            = '¯Ú';
    $EMOJI['ear']            = '¯Û';
    $EMOJI['goo']            = '¯Ù';
    $EMOJI['choki']          = '¯ı';
    $EMOJI['par']            = '¯ˆ';
    $EMOJI['right_down']     = '¯˜';
    $EMOJI['left_up']        = '¯¯';
    $EMOJI['foot']           = '¯˘';
    $EMOJI['shoes']          = '¯˙';
    $EMOJI['glasses']        = '¯˚';
    $EMOJI['wheelchair']     = '¯¸';
    $EMOJI['new_moon']       = '˘@';
    $EMOJI['chip_moon']      = '˘A';
    $EMOJI['half_moon']      = '˘B';
    $EMOJI['crescent_moon']  = '˘C';
    $EMOJI['full_moon']      = '˘D';
    $EMOJI['dog']            = '˘E';
    $EMOJI['cat']            = '˘F';
    $EMOJI['resort']         = '˘G';
    $EMOJI['xmas']           = '˘H';
    $EMOJI['left_down']      = '˘I';
    $EMOJI['kachinko']       = '˘P';
    $EMOJI['pouch']          = '˘Q';
    $EMOJI['pen']            = '˘R';
    $EMOJI['shadow']         = '˘U';
    $EMOJI['chair']          = '˘V';
    $EMOJI['night']          = '˘W';
    $EMOJI['soon']           = '˘[';
    $EMOJI['on']             = '˘\\';
    $EMOJI['end']            = '˘]';
    $EMOJI['clock']          = '˘^';
    $EMOJI['phone_to']       = '˘r';
    $EMOJI['mail_to']        = '˘s';
    $EMOJI['fax_to']         = '˘t';
    $EMOJI['carrier']        = '˘u';
    $EMOJI['carrier_2']      = '˘v';
    $EMOJI['mail']           = '˘w';
    $EMOJI['offer']          = '˘x';
    $EMOJI['point']          = '˘y';
    $EMOJI['yen']            = '˘z';
    $EMOJI['free']           = '˘{';
    $EMOJI['id']             = '˘|';
    $EMOJI['password']       = '˘}';
    $EMOJI['return']         = '˘~';
    $EMOJI['clear']          = '˘Ä';
    $EMOJI['search']         = '˘Å';
    $EMOJI['new']            = '˘Ç';
    $EMOJI['place']          = '˘É';
    $EMOJI['free_dial']      = '˘Ñ';
    $EMOJI['sharp_dial']     = '˘Ö';
    $EMOJI['mob_q']          = '˘Ü';
    $EMOJI['1']              = '˘á';
    $EMOJI['2']              = '˘à';
    $EMOJI['3']              = '˘â';
    $EMOJI['4']              = '˘ä';
    $EMOJI['5']              = '˘ã';
    $EMOJI['6']              = '˘å';
    $EMOJI['7']              = '˘ç';
    $EMOJI['8']              = '˘é';
    $EMOJI['9']              = '˘è';
    $EMOJI['0']              = '˘ê';
    $EMOJI['heart_black']    = '˘ë';
    $EMOJI['heart_wave']     = '˘í';
    $EMOJI['heart_break']    = '˘ì';
    $EMOJI['hearts']         = '˘î';
    $EMOJI['face_smile']     = '˘ï';
    $EMOJI['face_angry']     = '˘ñ';
    $EMOJI['face_deject']    = '˘ó';
    $EMOJI['face_sad']       = '˘ò';
    $EMOJI['face_swing']     = '˘ô';
    $EMOJI['good']           = '˘ö';
    $EMOJI['cheerful']       = '˘õ';
    $EMOJI['feel_good']      = '˘ú';
    $EMOJI['cute']           = '˘ù';
    $EMOJI['kiss']           = '˘û';
    $EMOJI['shine']          = '˘ü';
    $EMOJI['spark']          = '˘†';
    $EMOJI['anger']          = '˘°';
    $EMOJI['punch']          = '˘¢';
    $EMOJI['bomb']           = '˘£';
    $EMOJI['mood']           = '˘§';
    $EMOJI['bad']            = '˘•';
    $EMOJI['sleep']          = '˘¶';
    $EMOJI['exc']            = '˘ß';
    $EMOJI['exc_que']        = '˘®';
    $EMOJI['exc_2']          = '˘©';
    $EMOJI['shock']          = '˘™';
    $EMOJI['sweat']          = '˘´';
    $EMOJI['sweat_2']        = '˘¨';
    $EMOJI['dash']           = '˘≠';
    $EMOJI['long_vowel']     = '˘Æ';
    $EMOJI['long_vowel_2']   = '˘Ø';
    $EMOJI['ok']             = '˘∞';
    $EMOJI['appli']          = '˘±';
    $EMOJI['appli_2']        = '˘≤';
    $EMOJI['t-shirts']       = '˘≥';
    $EMOJI['wallet']         = '˘¥';
    $EMOJI['makeup']         = '˘µ';
    $EMOJI['jeans']          = '˘∂';
    $EMOJI['snow_board']     = '˘∑';
    $EMOJI['chapel']         = '˘∏';
    $EMOJI['door']           = '˘π';
    $EMOJI['dollar']         = '˘∫';
    $EMOJI['pc']             = '˘ª';
    $EMOJI['love_letter']    = '˘º';
    $EMOJI['wrench']         = '˘Ω';
    $EMOJI['pencil']         = '˘æ';
    $EMOJI['crown']          = '˘ø';
    $EMOJI['ring']           = '˘¿';
    $EMOJI['sandglass']      = '˘¡';
    $EMOJI['bicycle']        = '˘¬';
    $EMOJI['teacup']         = '˘√';
    $EMOJI['watch']          = '˘ƒ';
    $EMOJI['face_think']     = '˘≈';
    $EMOJI['face_peace']     = '˘∆';
    $EMOJI['face_hurry']     = '˘«';
    $EMOJI['face_hurry_2']   = '˘»';
    $EMOJI['face_angry_2']   = '˘…';
    $EMOJI['face_poker']     = '˘ ';
    $EMOJI['face_heart']     = '˘À';
    $EMOJI['finger']         = '˘Ã';
    $EMOJI['face_joke']      = '˘Õ';
    $EMOJI['face_wink']      = '˘Œ';
    $EMOJI['face_happy']     = '˘œ';
    $EMOJI['face_patience']  = '˘–';
    $EMOJI['cat_2']          = '˘—';
    $EMOJI['face_cry']       = '˘“';
    $EMOJI['tear']           = '˘”';
    $EMOJI['ng']             = '˘‘';
    $EMOJI['clip']           = '˘’';
    $EMOJI['copyright']      = '˘÷';
    $EMOJI['tm']             = '˘◊';
    $EMOJI['runner']         = '˘ÿ';
    $EMOJI['secret']         = '˘Ÿ';
    $EMOJI['recycling']      = '˘⁄';
    $EMOJI['regist']         = '˘€';
    $EMOJI['warning']        = '˘‹';
    $EMOJI['prohibition']    = '˘›';
    $EMOJI['empty']          = '˘ﬁ';
    $EMOJI['success']        = '˘ﬂ';
    $EMOJI['full']           = '˘‡';
    $EMOJI['right_left']     = '˘·';
    $EMOJI['up_down']        = '˘‚';
    $EMOJI['school']         = '˘„';
    $EMOJI['wave']           = '˘‰';
    $EMOJI['mountain']       = '˘Â';
    $EMOJI['clover']         = '˘Ê';
    $EMOJI['cherry']         = '˘Á';
    $EMOJI['tulip']          = '˘Ë';
    $EMOJI['banana']         = '˘È';
    $EMOJI['apple']          = '˘Í';
    $EMOJI['leaf']           = '˘Î';
    $EMOJI['maple']          = '˘Ï';
    $EMOJI['cherry_blossom'] = '˘Ì';
    $EMOJI['rice_ball']      = '˘Ó';
    $EMOJI['cake']           = '˘Ô';
    $EMOJI['sake']           = '˘';
    $EMOJI['bowl']           = '˘Ò';
    $EMOJI['pan']            = '˘Ú';
    $EMOJI['snail']          = '˘Û';
    $EMOJI['baby_bird']      = '˘Ù';
    $EMOJI['penguin']        = '˘ı';
    $EMOJI['fish']           = '˘ˆ';
    $EMOJI['face_delicious'] = '˘˜';
    $EMOJI['face_foppish']   = '˘¯';
    $EMOJI['horse']          = '˘˘';
    $EMOJI['pig']            = '˘˙';
    $EMOJI['wine']           = '˘˚';
    $EMOJI['face_let_down']  = '˘¸';
}

//i-modeÍ
$EMOJI_I[0] =  '¯ü';
$EMOJI_I[1] =  '¯†';
$EMOJI_I[2] =  '¯°';
$EMOJI_I[3] =  '¯¢';
$EMOJI_I[4] =  '¯£';
$EMOJI_I[5] =  '¯§';
$EMOJI_I[6] =  '¯•';
$EMOJI_I[7] =  '¯¶';
$EMOJI_I[8] =  '¯ß';
$EMOJI_I[9] =  '¯®';
$EMOJI_I[10] = '¯©';
$EMOJI_I[11] = '¯™';
$EMOJI_I[12] = '¯´';
$EMOJI_I[13] = '¯¨';
$EMOJI_I[14] = '¯≠';
$EMOJI_I[15] = '¯Æ';
$EMOJI_I[16] = '¯Ø';
$EMOJI_I[17] = '¯∞';
$EMOJI_I[18] = '¯±';
$EMOJI_I[19] = '¯≤';
$EMOJI_I[20] = '¯≥';
$EMOJI_I[21] = '¯¥';
$EMOJI_I[22] = '¯µ';
$EMOJI_I[23] = '¯∂';
$EMOJI_I[24] = '¯∑';
$EMOJI_I[25] = '¯∏';
$EMOJI_I[26] = '¯π';
$EMOJI_I[27] = '¯∫';
$EMOJI_I[28] = '¯ª';
$EMOJI_I[29] = '¯º';
$EMOJI_I[30] = '¯Ω';
$EMOJI_I[31] = '¯æ';
$EMOJI_I[32] = '¯ø';
$EMOJI_I[33] = '¯¿';
$EMOJI_I[34] = '¯¡';
$EMOJI_I[35] = '¯¬';
$EMOJI_I[36] = '¯√';
$EMOJI_I[37] = '¯ƒ';
$EMOJI_I[38] = '¯≈';
$EMOJI_I[39] = '¯∆';
$EMOJI_I[40] = '¯«';
$EMOJI_I[41] = '¯»';
$EMOJI_I[42] = '¯…';
$EMOJI_I[43] = '¯ ';
$EMOJI_I[44] = '¯À';
$EMOJI_I[45] = '¯Ã';
$EMOJI_I[46] = '¯Õ';
$EMOJI_I[47] = '¯Œ';
$EMOJI_I[48] = '¯œ';
$EMOJI_I[49] = '¯–';
$EMOJI_I[50] = '¯—';
$EMOJI_I[51] = '¯“';
$EMOJI_I[52] = '¯”';
$EMOJI_I[53] = '¯‘';
$EMOJI_I[54] = '¯’';
$EMOJI_I[55] = '¯÷';
$EMOJI_I[56] = '¯◊';
$EMOJI_I[57] = '¯ÿ';
$EMOJI_I[58] = '¯Ÿ';
$EMOJI_I[59] = '¯⁄';
$EMOJI_I[60] = '¯€';
$EMOJI_I[61] = '¯‹';
$EMOJI_I[62] = '¯›';
$EMOJI_I[63] = '¯ﬁ';
$EMOJI_I[64] = '¯ﬂ';
$EMOJI_I[65] = '¯‡';
$EMOJI_I[66] = '¯·';
$EMOJI_I[67] = '¯‚';
$EMOJI_I[68] = '¯„';
$EMOJI_I[69] = '¯‰';
$EMOJI_I[70] = '¯Â';
$EMOJI_I[71] = '¯Ê';
$EMOJI_I[72] = '¯Á';
$EMOJI_I[73] = '¯Ë';
$EMOJI_I[74] = '¯È';
$EMOJI_I[75] = '¯Í';
$EMOJI_I[76] = '¯Î';
$EMOJI_I[77] = '¯Ï';
$EMOJI_I[78] = '¯Ì';
$EMOJI_I[79] = '¯Ó';
$EMOJI_I[80] = '¯Ô';
$EMOJI_I[81] = '¯';
$EMOJI_I[82] = '¯Ò';
$EMOJI_I[83] = '¯Ú';
$EMOJI_I[84] = '¯Û';
$EMOJI_I[85] = '¯Ù';
$EMOJI_I[86] = '¯ı';
$EMOJI_I[87] = '¯ˆ';
$EMOJI_I[88] = '¯˜';
$EMOJI_I[89] = '¯¯';
$EMOJI_I[90] = '¯˘';
$EMOJI_I[91] = '¯˙';
$EMOJI_I[92] = '¯˚';
$EMOJI_I[93] = '¯¸';
$EMOJI_I[94] = '˘@';
$EMOJI_I[95] = '˘A';
$EMOJI_I[96] = '˘B';
$EMOJI_I[97] = '˘C';
$EMOJI_I[98] = '˘D';
$EMOJI_I[99] = '˘E';
$EMOJI_I[100] ='˘F';
$EMOJI_I[101] ='˘G';
$EMOJI_I[102] ='˘H';
$EMOJI_I[103] ='˘I';
$EMOJI_I[104] ='˘P';
$EMOJI_I[105] ='˘Q';
$EMOJI_I[106] ='˘R';
$EMOJI_I[107] ='˘U';
$EMOJI_I[108] ='˘V';
$EMOJI_I[109] ='˘W';
$EMOJI_I[110] ='˘[';
$EMOJI_I[111] ='˘\\';
$EMOJI_I[112] ='˘]';
$EMOJI_I[113] ='˘^';
$EMOJI_I[114] ='˘r';
$EMOJI_I[115] ='˘s';
$EMOJI_I[116] ='˘t';
$EMOJI_I[117] ='˘u';
$EMOJI_I[118] ='˘v';
$EMOJI_I[119] ='˘w';
$EMOJI_I[120] ='˘x';
$EMOJI_I[121] ='˘y';
$EMOJI_I[122] ='˘z';
$EMOJI_I[123] ='˘{';
$EMOJI_I[124] ='˘|';
$EMOJI_I[125] ='˘}';
$EMOJI_I[126] ='˘~';
$EMOJI_I[127] ='˘Ä';
$EMOJI_I[128] ='˘Å';
$EMOJI_I[129] ='˘Ç';
$EMOJI_I[130] ='˘É';
$EMOJI_I[131] ='˘Ñ';
$EMOJI_I[132] ='˘Ö';
$EMOJI_I[133] ='˘Ü';
$EMOJI_I[134] ='˘á';
$EMOJI_I[135] ='˘à';
$EMOJI_I[136] ='˘â';
$EMOJI_I[137] ='˘ä';
$EMOJI_I[138] ='˘ã';
$EMOJI_I[139] ='˘å';
$EMOJI_I[140] ='˘ç';
$EMOJI_I[141] ='˘é';
$EMOJI_I[142] ='˘è';
$EMOJI_I[143] ='˘ê';
$EMOJI_I[144] ='˘ë';
$EMOJI_I[145] ='˘í';
$EMOJI_I[146] ='˘ì';
$EMOJI_I[147] ='˘î';
$EMOJI_I[148] ='˘ï';
$EMOJI_I[149] ='˘ñ';
$EMOJI_I[150] ='˘ó';
$EMOJI_I[151] ='˘ò';
$EMOJI_I[152] ='˘ô';
$EMOJI_I[153] ='˘ö';
$EMOJI_I[154] ='˘õ';
$EMOJI_I[155] ='˘ú';
$EMOJI_I[156] ='˘ù';
$EMOJI_I[157] ='˘û';
$EMOJI_I[158] ='˘ü';
$EMOJI_I[159] ='˘†';
$EMOJI_I[160] ='˘°';
$EMOJI_I[161] ='˘¢';
$EMOJI_I[162] ='˘£';
$EMOJI_I[163] ='˘§';
$EMOJI_I[164] ='˘•';
$EMOJI_I[165] ='˘¶';
$EMOJI_I[166] ='˘ß';
$EMOJI_I[167] ='˘®';
$EMOJI_I[168] ='˘©';
$EMOJI_I[169] ='˘™';
$EMOJI_I[170] ='˘´';
$EMOJI_I[171] ='˘¨';
$EMOJI_I[172] ='˘≠';
$EMOJI_I[173] ='˘Æ';
$EMOJI_I[174] ='˘Ø';
$EMOJI_I[175] ='˘∞';
$EMOJI_I[176] ='˘±';
$EMOJI_I[177] ='˘≤';
$EMOJI_I[178] ='˘≥';
$EMOJI_I[179] ='˘¥';
$EMOJI_I[180] ='˘µ';
$EMOJI_I[181] ='˘∂';
$EMOJI_I[182] ='˘∑';
$EMOJI_I[183] ='˘∏';
$EMOJI_I[184] ='˘π';
$EMOJI_I[185] ='˘∫';
$EMOJI_I[186] ='˘ª';
$EMOJI_I[187] ='˘º';
$EMOJI_I[188] ='˘Ω';
$EMOJI_I[189] ='˘æ';
$EMOJI_I[190] ='˘ø';
$EMOJI_I[191] ='˘¿';
$EMOJI_I[192] ='˘¡';
$EMOJI_I[193] ='˘¬';
$EMOJI_I[194] ='˘√';
$EMOJI_I[195] ='˘ƒ';
$EMOJI_I[196] ='˘≈';
$EMOJI_I[197] ='˘∆';
$EMOJI_I[198] ='˘«';
$EMOJI_I[199] ='˘»';
$EMOJI_I[200] ='˘…';
$EMOJI_I[201] ='˘ ';
$EMOJI_I[202] ='˘À';
$EMOJI_I[203] ='˘Ã';
$EMOJI_I[204] ='˘Õ';
$EMOJI_I[205] ='˘Œ';
$EMOJI_I[206] ='˘œ';
$EMOJI_I[207] ='˘–';
$EMOJI_I[208] ='˘—';
$EMOJI_I[209] ='˘“';
$EMOJI_I[210] ='˘”';
$EMOJI_I[211] ='˘‘';
$EMOJI_I[212] ='˘’';
$EMOJI_I[213] ='˘÷';
$EMOJI_I[214] ='˘◊';
$EMOJI_I[215] ='˘ÿ';
$EMOJI_I[216] ='˘Ÿ';
$EMOJI_I[217] ='˘⁄';
$EMOJI_I[218] ='˘€';
$EMOJI_I[219] ='˘‹';
$EMOJI_I[220] ='˘›';
$EMOJI_I[221] ='˘ﬁ';
$EMOJI_I[222] ='˘ﬂ';
$EMOJI_I[223] ='˘‡';
$EMOJI_I[224] ='˘·';
$EMOJI_I[225] ='˘‚';
$EMOJI_I[226] ='˘„';
$EMOJI_I[227] ='˘‰';
$EMOJI_I[228] ='˘Â';
$EMOJI_I[229] ='˘Ê';
$EMOJI_I[230] ='˘Á';
$EMOJI_I[231] ='˘Ë';
$EMOJI_I[232] ='˘È';
$EMOJI_I[233] ='˘Í';
$EMOJI_I[234] ='˘Î';
$EMOJI_I[235] ='˘Ï';
$EMOJI_I[236] ='˘Ì';
$EMOJI_I[237] ='˘Ó';
$EMOJI_I[238] ='˘Ô';
$EMOJI_I[239] ='˘';
$EMOJI_I[240] ='˘Ò';
$EMOJI_I[241] ='˘Ú';
$EMOJI_I[242] ='˘Û';
$EMOJI_I[243] ='˘Ù';
$EMOJI_I[244] ='˘ı';
$EMOJI_I[245] ='˘ˆ';
$EMOJI_I[246] ='˘˜';
$EMOJI_I[247] ='˘¯';
$EMOJI_I[248] ='˘˘';
$EMOJI_I[249] ='˘˙';
$EMOJI_I[250] ='˘˚';
$EMOJI_I[251] ='˘¸';

//SoftbankÍ
$EMOJI_V[0]            = '$Gj';
$EMOJI_V[1]            = '$Gi';
$EMOJI_V[2]            = '$Gk';
$EMOJI_V[3]            = '$Gh';
$EMOJI_V[4]            = '$E]';
$EMOJI_V[5]            = '$E]';
$EMOJI_V[6]            = '$Gi';
$EMOJI_V[7]            = '$Gk';
$EMOJI_V[8]            = '$F_';
$EMOJI_V[9]            = '$F`';
$EMOJI_V[10]           = '$Fa';
$EMOJI_V[11]           = '$Fb';
$EMOJI_V[12]           = '$Fc';
$EMOJI_V[13]           = '$Fd';
$EMOJI_V[14]           = '$Fe';
$EMOJI_V[15]           = '$Ff';
$EMOJI_V[16]           = '$Fg';
$EMOJI_V[17]           = '$Fh';
$EMOJI_V[18]           = '$Fi';
$EMOJI_V[19]           = '$Fj';
$EMOJI_V[20]           = '$G&';
$EMOJI_V[21]           = '$G6';
$EMOJI_V[22]           = '$G4';
$EMOJI_V[23]           = '$G5';
$EMOJI_V[24]           = '$G8';
$EMOJI_V[25]           = '$G3';
$EMOJI_V[26]           = '$E5';
$EMOJI_V[27]           = '$ER';
$EMOJI_V[28]           = '$G*';
$EMOJI_V[29]           = '$G>';
$EMOJI_V[30]           = '$G>';
$EMOJI_V[31]           = '$G?';
$EMOJI_V[32]           = '$G;';
$EMOJI_V[33]           = '$G;';
$EMOJI_V[34]           = '$Ey';
$EMOJI_V[35]           = '$F"';
$EMOJI_V[36]           = '$G=';
$EMOJI_V[37]           = '$GV';
$EMOJI_V[38]           = '$GX';
$EMOJI_V[39]           = '$Es';
$EMOJI_V[40]           = '$Eu';
$EMOJI_V[41]           = '$Em';
$EMOJI_V[42]           = '$Et';
$EMOJI_V[43]           = '$Ex';
$EMOJI_V[44]           = '$Ev';
$EMOJI_V[45]           = '$GZ';
$EMOJI_V[46]           = '$Eo';
$EMOJI_V[47]           = '$En';
$EMOJI_V[48]           = '$Eq';
$EMOJI_V[49]           = '$Gc';
$EMOJI_V[50]           = '$Ge';
$EMOJI_V[51]           = '$Gd';
$EMOJI_V[52]           = '$Gg';
$EMOJI_V[53]           = '$E@';
$EMOJI_V[54]           = '$E^';
$EMOJI_V[55]           = '$E?';
$EMOJI_V[56]           = '$G\';
$EMOJI_V[57]           = '$G]';
$EMOJI_V[58]           = '$FV';
$EMOJI_V[59]           = '$ED';
$EMOJI_V[60]           = '$G\';
$EMOJI_V[61]           = '$GR';
$EMOJI_V[62]           = '$E1';
$EMOJI_V[63]           = '$E7';
$EMOJI_V[64]           = '$EE';
$EMOJI_V[65]           = '$O.';
$EMOJI_V[66]           = '$F(';
$EMOJI_V[67]           = '$G(';
$EMOJI_V[68]           = '$E>';
$EMOJI_V[69]           = '$Eh';
$EMOJI_V[70]           = '$E2';
$EMOJI_V[71]           = '$E2';
$EMOJI_V[72]           = '$Ok';
$EMOJI_V[73]           = '$G)';
$EMOJI_V[74]           = '$G*';
$EMOJI_V[75]           = '$Eh';
$EMOJI_V[76]           = '$EJ';
$EMOJI_V[77]           = '$EK';
$EMOJI_V[78]           = '$EF';
$EMOJI_V[79]           = '$F,';
$EMOJI_V[80]           = '$F.';
$EMOJI_V[81]           = '$F-';
$EMOJI_V[82]           = '$F/';
$EMOJI_V[83]           = '$E4';
$EMOJI_V[84]           = '$Ea';
$EMOJI_V[85]           = '$G0';
$EMOJI_V[86]           = '$G1';
$EMOJI_V[87]           = '$G2';
$EMOJI_V[88]           = '$FX';
$EMOJI_V[89]           = '$FW';
$EMOJI_V[90]           = '$G\'';
$EMOJI_V[91]           = '$G\'';
$EMOJI_V[92]           = '$E4';
$EMOJI_V[93]           = '$F*';
$EMOJI_V[94]           = '$Gl';   //
$EMOJI_V[95]           = '$Gl';   //
$EMOJI_V[96]           = '$Gl';   //
$EMOJI_V[97]           = '$Gl';
$EMOJI_V[98]           = '$Gl';   //
$EMOJI_V[99]           = '$Gr';
$EMOJI_V[100]          = '$Go';
$EMOJI_V[101]          = '$G:';
$EMOJI_V[102]          = '$GS';
$EMOJI_V[103]          = '$FY';
$EMOJI_V[104]          = '$G]';
$EMOJI_V[105]          = '$E>';
$EMOJI_V[106]          = '$O!';
$EMOJI_V[107]          = '$EX';
$EMOJI_V[108]          = '$E?';   //
$EMOJI_V[109]          = '$Ef';
$EMOJI_V[110]          = '$F\';   //
$EMOJI_V[111]          = '$F3';   //
$EMOJI_V[112]          = '$F]';   //
$EMOJI_V[113]          = '$GG';
$EMOJI_V[114]          = '$E$';
$EMOJI_V[115]          = '$E#';
$EMOJI_V[116]          = '$G+';
$EMOJI_V[117]          = '$Fu';    
$EMOJI_V[118]          = '$Fu';    
$EMOJI_V[119]          = '$E#';
$EMOJI_V[120]          = '$Ft';    
$EMOJI_V[121]          = '$Fu';    
$EMOJI_V[122]          = '$F5';
$EMOJI_V[123]          = '$F6';
$EMOJI_V[124]          = '$FI';
$EMOJI_V[125]          = '$G_';
$EMOJI_V[126]          = '$FP';
$EMOJI_V[127]          = '$F6';
$EMOJI_V[128]          = '$E4';
$EMOJI_V[129]          = '$F2';
$EMOJI_V[130]          = '$F#';
$EMOJI_V[131]          = '$F1';
$EMOJI_V[132]          = '$F0';
$EMOJI_V[133]          = '$G*';
$EMOJI_V[134]          = '$F<';
$EMOJI_V[135]          = '$F=';
$EMOJI_V[136]          = '$F>';
$EMOJI_V[137]          = '$F?';
$EMOJI_V[138]          = '$F@';
$EMOJI_V[139]          = '$FA';
$EMOJI_V[140]          = '$FB';
$EMOJI_V[141]          = '$FC';
$EMOJI_V[142]          = '$FD';
$EMOJI_V[143]          = '$FE';
$EMOJI_V[144]          = '$GB';
$EMOJI_V[145]          = '$GB';
$EMOJI_V[146]          = '$GC';
$EMOJI_V[147]          = '$GB';
$EMOJI_V[148]          = '$Gw';
$EMOJI_V[149]          = '$Gy';
$EMOJI_V[150]          = '$Gx';
$EMOJI_V[151]          = '$Gx';
$EMOJI_V[152]          = '$E\'';
$EMOJI_V[153]          = '$G.';
$EMOJI_V[154]          = '$G^';
$EMOJI_V[155]          = '$EC';
$EMOJI_V[156]          = '$F$';
$EMOJI_V[157]          = '$G#';
$EMOJI_V[158]          = '$F9';
$EMOJI_V[159]          = '$E/';
$EMOJI_V[160]          = '$Gy';
$EMOJI_V[161]          = '$G-';
$EMOJI_V[162]          = '$E7';
$EMOJI_V[163]          = '$G^';
$EMOJI_V[164]          = '$FY';
$EMOJI_V[165]          = '$E\';
$EMOJI_V[166]          = '$GA';
$EMOJI_V[167]          = '$GA$G@';
$EMOJI_V[168]          = '$GA$GA';
$EMOJI_V[169]          = '$E-';
$EMOJI_V[170]          = '$OQ';
$EMOJI_V[171]          = '$E(';
$EMOJI_V[172]          = '$OP';
$EMOJI_V[173]          = '$FT';
$EMOJI_V[174]          = '$F1';
$EMOJI_V[175]          = '$Fm';
$EMOJI_V[176]          = '$Fw';    
$EMOJI_V[177]          = '$Fw';    
$EMOJI_V[178]          = '$G&';
$EMOJI_V[179]          = '$EO';
$EMOJI_V[180]          = '$G#';
$EMOJI_V[181]          = '$O9';
$EMOJI_V[182]          = '$G3';
$EMOJI_V[183]          = '$GW';
$EMOJI_V[184]          = '$GV';
$EMOJI_V[185]          = '$EO';
$EMOJI_V[186]          = '$G,';
$EMOJI_V[187]          = '$E!';
$EMOJI_V[188]          = '$E6';
$EMOJI_V[189]          = '$O!';
$EMOJI_V[190]          = '$E.';
$EMOJI_V[191]          = '$GT';
$EMOJI_V[192]          = '$GO';
$EMOJI_V[193]          = '$EV';
$EMOJI_V[194]          = '$Ge';
$EMOJI_V[195]          = '$GG';
$EMOJI_V[196]          = '$Gx';
$EMOJI_V[197]          = '$Gv';
$EMOJI_V[198]          = '$E(';
$EMOJI_V[199]          = '$E(';
$EMOJI_V[200]          = '$Gy';
$EMOJI_V[201]          = '$Gv';
$EMOJI_V[202]          = '$E&';
$EMOJI_V[203]          = '$G.';
$EMOJI_V[204]          = '$E%';
$EMOJI_V[205]          = '$E%';
$EMOJI_V[206]          = '$Gw';
$EMOJI_V[207]          = '$Gx';
$EMOJI_V[208]          = '$Go';
$EMOJI_V[209]          = '$Gx';
$EMOJI_V[210]          = '$Gx';
$EMOJI_V[211]          = '$F\'';
$EMOJI_V[212]          = '$O!';
$EMOJI_V[213]          = '$Fn';
$EMOJI_V[214]          = '$QW';
$EMOJI_V[215]          = '$E5';
$EMOJI_V[216]          = '$Ed';
$EMOJI_V[217]          = '$ON';
$EMOJI_V[218]          = '$Fo';
$EMOJI_V[219]          = '$Fr';
$EMOJI_V[220]          = '$F\'';
$EMOJI_V[221]          = '$FK';
$EMOJI_V[222]          = '$G.';
$EMOJI_V[223]          = '$FJ';
$EMOJI_V[224]          = '$FU$FT';
$EMOJI_V[225]          = '$FR$FS';
$EMOJI_V[226]          = '$Ew';
$EMOJI_V[227]          = '$G7';
$EMOJI_V[228]          = '$G[';
$EMOJI_V[229]          = '$E0';
$EMOJI_V[230]          = '$Og';
$EMOJI_V[231]          = '$O$';
$EMOJI_V[232]          = '$Of';
$EMOJI_V[233]          = '$Oe';
$EMOJI_V[234]          = '$E0';
$EMOJI_V[235]          = '$E8';
$EMOJI_V[236]          = '$GP';
$EMOJI_V[237]          = '$Ob';
$EMOJI_V[238]          = '$Gf';
$EMOJI_V[239]          = '$O+';
$EMOJI_V[240]          = '$OX';
$EMOJI_V[241]          = '$OY';
$EMOJI_V[242]          = '$QQ';
$EMOJI_V[243]          = '$QC';
$EMOJI_V[244]          = '$Gu';
$EMOJI_V[245]          = '$G9';
$EMOJI_V[246]          = '$Gv';
$EMOJI_V[247]          = '$Gw';
$EMOJI_V[248]          = '$G:';
$EMOJI_V[249]          = '$E+';
$EMOJI_V[250]          = '$Gd';
$EMOJI_V[251]          = '$E\'';

//ez
if(!$hdml_flg){
    $EMOJI_E['0'] = '<img localsrc="44">'; 
    $EMOJI_E['1'] = '<img localsrc="107">'; 
    $EMOJI_E['2'] = '<img localsrc="95">'; 
    $EMOJI_E['3'] = '<img localsrc="191">'; 
    $EMOJI_E['4'] = '<img localsrc="16">'; 
    $EMOJI_E['5'] = '<img localsrc="190">'; 
    $EMOJI_E['6'] = '<img localsrc="305">'; 
    $EMOJI_E['7'] = '<img localsrc="481">'; 
    $EMOJI_E['8'] = '<img localsrc="192">'; 
    $EMOJI_E['9'] = '<img localsrc="193">'; 
    $EMOJI_E['10'] = '<img localsrc="194">'; 
    $EMOJI_E['11'] = '<img localsrc="195">'; 
    $EMOJI_E['12'] = '<img localsrc="196">'; 
    $EMOJI_E['13'] = '<img localsrc="197">'; 
    $EMOJI_E['14'] = '<img localsrc="198">'; 
    $EMOJI_E['15'] = '<img localsrc="199">'; 
    $EMOJI_E['16'] = '<img localsrc="200">'; 
    $EMOJI_E['17'] = '<img localsrc="201">'; 
    $EMOJI_E['18'] = '<img localsrc="202">'; 
    $EMOJI_E['19'] = '<img localsrc="203">'; 
    $EMOJI_E['20'] = '<img localsrc="218">'; 
    $EMOJI_E['21'] = '<img localsrc="45">'; 
    $EMOJI_E['22'] = '<img localsrc="306">'; 
    $EMOJI_E['23'] = '<img localsrc="220">'; 
    $EMOJI_E['24'] = '<img localsrc="219">'; 
    $EMOJI_E['25'] = '<img localsrc="421">'; 
    $EMOJI_E['26'] = '<img localsrc="307">'; 
    $EMOJI_E['27'] = '<img localsrc="222">'; 
    $EMOJI_E['28'] = '<img localsrc="308">'; 
    $EMOJI_E['29'] = '<img localsrc="172">'; 
    $EMOJI_E['30'] = '<img localsrc="341">'; 
    $EMOJI_E['31'] = '<img localsrc="217">'; 
    $EMOJI_E['32'] = '<img localsrc="125">'; 
    $EMOJI_E['33'] = '<img localsrc="125">'; 
    $EMOJI_E['34'] = '<img localsrc="216">'; 
    $EMOJI_E['35'] = '<img localsrc="379">'; 
    $EMOJI_E['36'] = '<img localsrc="168">'; 
    $EMOJI_E['37'] = '<img localsrc="112">'; 
    $EMOJI_E['38'] = '<img localsrc="156">'; 
    $EMOJI_E['39'] = '<img localsrc="375">'; 
    $EMOJI_E['40'] = '<img localsrc="376">'; 
    $EMOJI_E['41'] = '<img localsrc="212">'; 
    $EMOJI_E['42'] = '<img localsrc="205">'; 
    $EMOJI_E['43'] = '<img localsrc="378">'; 
    $EMOJI_E['44'] = '<img localsrc="206">'; 
    $EMOJI_E['45'] = '<img localsrc="213">'; 
    $EMOJI_E['46'] = '<img localsrc="208">'; 
    $EMOJI_E['47'] = '<img localsrc="99">'; 
    $EMOJI_E['48'] = '<img localsrc="207">'; 
    $EMOJI_E['49'] = '<img localsrc="146">'; 
    $EMOJI_E['50'] = '<img localsrc="93">'; 
    $EMOJI_E['51'] = '<img localsrc="52">'; 
    $EMOJI_E['52'] = '<img localsrc="65">'; 
    $EMOJI_E['53'] = '<img localsrc="245">'; 
    $EMOJI_E['54'] = '<img localsrc="124">'; 
    $EMOJI_E['55'] = '<img localsrc="104">'; 
    $EMOJI_E['56'] = '<img localsrc="289">'; 
    $EMOJI_E['57'] = '<img localsrc="110">'; 
    $EMOJI_E['58'] = '<img localsrc="70">'; 
    $EMOJI_E['59'] = '<img localsrc="223">'; 
    $EMOJI_E['60'] = '<img localsrc="294">'; 
    $EMOJI_E['61'] = '<img localsrc="309">'; 
    $EMOJI_E['62'] = '<img localsrc="310">'; 
    $EMOJI_E['63'] = '<img localsrc="311">'; 
    $EMOJI_E['64'] = '<img localsrc="106">'; 
    $EMOJI_E['65'] = '<img localsrc="176">'; 
    $EMOJI_E['66'] = '<img localsrc="177">'; 
    $EMOJI_E['67'] = '<img localsrc="94">'; 
    $EMOJI_E['68'] = '<img localsrc="83">'; 
    $EMOJI_E['69'] = '<img localsrc="122">'; 
    $EMOJI_E['70'] = '<img localsrc="312">'; 
    $EMOJI_E['71'] = '<img localsrc="144">'; 
    $EMOJI_E['72'] = '<img localsrc="313">'; 
    $EMOJI_E['73'] = '<img localsrc="85">'; 
    $EMOJI_E['74'] = '<img localsrc="161">'; 
    $EMOJI_E['75'] = '<img localsrc="56">'; 
    $EMOJI_E['76'] = '<img localsrc="288">'; 
    $EMOJI_E['77'] = '<img localsrc="232">'; 
    $EMOJI_E['78'] = '<img localsrc="300">'; 
    $EMOJI_E['79'] = '<img localsrc="414">'; 
    $EMOJI_E['80'] = '<img localsrc="314">'; 
    $EMOJI_E['81'] = '<img localsrc="315">'; 
    $EMOJI_E['82'] = '<img localsrc="316">'; 
    $EMOJI_E['83'] = '<img localsrc="317">'; 
    $EMOJI_E['84'] = '<img localsrc="318">'; 
    $EMOJI_E['85'] = '<img localsrc="817">'; 
    $EMOJI_E['86'] = '<img localsrc="319">'; 
    $EMOJI_E['87'] = '<img localsrc="320">'; 
    $EMOJI_E['88'] = '<img localsrc="43">'; 
    $EMOJI_E['89'] = '<img localsrc="42">'; 
    $EMOJI_E['90'] = '<img localsrc="728">'; 
    $EMOJI_E['91'] = '<img localsrc="729">'; 
    $EMOJI_E['92'] = '<img localsrc="116">'; 
    $EMOJI_E['93'] = '<img localsrc="178">'; 
    $EMOJI_E['94'] = '<img localsrc="321">'; 
    $EMOJI_E['95'] = '<img localsrc="322">'; 
    $EMOJI_E['96'] = '<img localsrc="323">'; 
    $EMOJI_E['97'] = '<img localsrc="15">'; 
    $EMOJI_E['98'] = '<img localsrc="47">'; 
    $EMOJI_E['99'] = '<img localsrc="134">'; 
    $EMOJI_E['100'] = '<img localsrc="251">'; 
    $EMOJI_E['101'] = '<img localsrc="169">'; 
    $EMOJI_E['102'] = '<img localsrc="234">'; 
    $EMOJI_E['103'] = '<img localsrc="71">'; 
    $EMOJI_E['104'] = '<img localsrc="226">'; 
    $EMOJI_E['105'] = '<img localsrc="233">'; 
    $EMOJI_E['106'] = '<img localsrc="508">'; 
    $EMOJI_E['107'] = '<img localsrc="80">'; 
    $EMOJI_E['108'] = ''; 
    $EMOJI_E['109'] = '<img localsrc="227">'; 
    $EMOJI_E['110'] = '<img localsrc="63">'; 
    $EMOJI_E['111'] = '<img localsrc="808">'; 
    $EMOJI_E['112'] = '<img localsrc="64">'; 
    $EMOJI_E['113'] = '<img localsrc="46">'; 
    $EMOJI_E['114'] = '<img localsrc="513">'; 
    $EMOJI_E['115'] = '<img localsrc="784">'; 
    $EMOJI_E['116'] = '<img localsrc="166">'; 
    $EMOJI_E['117'] = 'i'; 
    $EMOJI_E['118'] = 'i'; 
    $EMOJI_E['119'] = '<img localsrc="108">'; 
    $EMOJI_E['120'] = 'D'; 
    $EMOJI_E['121'] = 'D'; 
    $EMOJI_E['122'] = '<img localsrc="109">'; 
    $EMOJI_E['123'] = '<img localsrc="299">'; 
    $EMOJI_E['124'] = '<img localsrc="385">'; 
    $EMOJI_E['125'] = '<img localsrc="120">'; 
    $EMOJI_E['126'] = '<img localsrc="118">'; 
    $EMOJI_E['127'] = '<img localsrc="324">'; 
    $EMOJI_E['128'] = '<img localsrc="119">'; 
    $EMOJI_E['129'] = '<img localsrc="334">'; 
    $EMOJI_E['130'] = '<img localsrc="730">'; 
    $EMOJI_E['131'] = 'F'; 
    $EMOJI_E['132'] = '#'; 
    $EMOJI_E['133'] = 'Q'; 
    $EMOJI_E['134'] = '<img localsrc="180">'; 
    $EMOJI_E['135'] = '<img localsrc="181">'; 
    $EMOJI_E['136'] = '<img localsrc="182">'; 
    $EMOJI_E['137'] = '<img localsrc="183">'; 
    $EMOJI_E['138'] = '<img localsrc="184">'; 
    $EMOJI_E['139'] = '<img localsrc="185">'; 
    $EMOJI_E['140'] = '<img localsrc="186">'; 
    $EMOJI_E['141'] = '<img localsrc="187">'; 
    $EMOJI_E['142'] = '<img localsrc="188">'; 
    $EMOJI_E['143'] = '<img localsrc="325">'; 
    $EMOJI_E['144'] = '<img localsrc="51">'; 
    $EMOJI_E['145'] = '<img localsrc="328">'; 
    $EMOJI_E['146'] = '<img localsrc="265">'; 
    $EMOJI_E['147'] = '<img localsrc="266">'; 
    $EMOJI_E['148'] = '<img localsrc="257">'; 
    $EMOJI_E['149'] = '<img localsrc="258">'; 
    $EMOJI_E['150'] = '<img localsrc="260">'; 
    $EMOJI_E['151'] = '<img localsrc="259">'; 
    $EMOJI_E['152'] = '<img localsrc="327">'; 
    $EMOJI_E['153'] = '<img localsrc="731">'; 
    $EMOJI_E['154'] = '<img localsrc="343">'; 
    $EMOJI_E['155'] = '<img localsrc="224">'; 
    $EMOJI_E['156'] = '<img localsrc="19">'; 
    $EMOJI_E['157'] = '<img localsrc="273">'; 
    $EMOJI_E['158'] = '<img localsrc="420">'; 
    $EMOJI_E['159'] = '<img localsrc="77">'; 
    $EMOJI_E['160'] = '<img localsrc="262">'; 
    $EMOJI_E['161'] = '<img localsrc="281">'; 
    $EMOJI_E['162'] = '<img localsrc="268">'; 
    $EMOJI_E['163'] = '<img localsrc="291">'; 
    $EMOJI_E['164'] = '<img localsrc="732">'; 
    $EMOJI_E['165'] = '<img localsrc="261">'; 
    $EMOJI_E['166'] = '<img localsrc="2">'; 
    $EMOJI_E['167'] = '<img localsrc="733">'; 
    $EMOJI_E['168'] = '<img localsrc="734">'; 
    $EMOJI_E['169'] = '<img localsrc="329">'; 
    $EMOJI_E['170'] = '<img localsrc="330">'; 
    $EMOJI_E['171'] = '<img localsrc="263">'; 
    $EMOJI_E['172'] = '<img localsrc="282">'; 
    $EMOJI_E['173'] = '<img localsrc="810">'; 
    $EMOJI_E['174'] = '<img localsrc="735">'; 
    $EMOJI_E['175'] = '<img localsrc="326">'; 
    $EMOJI_E['176'] = 'Éø'; 
    $EMOJI_E['177'] = 'Éø'; 
    $EMOJI_E['178'] = '<img localsrc="335">'; 
    $EMOJI_E['179'] = '<img localsrc="290">'; 
    $EMOJI_E['180'] = '<img localsrc="295">'; 
    $EMOJI_E['181'] = '<img localsrc="805">'; 
    $EMOJI_E['182'] = '<img localsrc="221">'; 
    $EMOJI_E['183'] = '<img localsrc="48">'; 
    $EMOJI_E['184'] = ''; 
    $EMOJI_E['185'] = '<img localsrc="233">'; 
    $EMOJI_E['186'] = '<img localsrc="337">'; 
    $EMOJI_E['187'] = '<img localsrc="806">'; 
    $EMOJI_E['188'] = '<img localsrc="152">'; 
    $EMOJI_E['189'] = '<img localsrc="149">'; 
    $EMOJI_E['190'] = '<img localsrc="354">'; 
    $EMOJI_E['191'] = '<img localsrc="72">'; 
    $EMOJI_E['192'] = '<img localsrc="58">'; 
    $EMOJI_E['193'] = '<img localsrc="215">'; 
    $EMOJI_E['194'] = '<img localsrc="423">'; 
    $EMOJI_E['195'] = '<img localsrc="25">'; 
    $EMOJI_E['196'] = '<img localsrc="443">'; 
    $EMOJI_E['197'] = '<img localsrc="454">'; 
    $EMOJI_E['198'] = '<img localsrc="351">'; 
    $EMOJI_E['199'] = '<img localsrc="351">'; 
    $EMOJI_E['200'] = '<img localsrc="779">'; 
    $EMOJI_E['201'] = '<img localsrc="789">'; 
    $EMOJI_E['202'] = '<img localsrc="349">'; 
    $EMOJI_E['203'] = '<img localsrc="287">'; 
    $EMOJI_E['204'] = '<img localsrc="264">'; 
    $EMOJI_E['205'] = '<img localsrc="348">'; 
    $EMOJI_E['206'] = '<img localsrc="257">'; 
    $EMOJI_E['207'] = '<img localsrc="260">'; 
    $EMOJI_E['208'] = '<img localsrc="783">'; 
    $EMOJI_E['209'] = '<img localsrc="259">'; 
    $EMOJI_E['210'] = '<img localsrc="791">'; 
    $EMOJI_E['211'] = ''; 
    $EMOJI_E['212'] = '<img localsrc="143">'; 
    $EMOJI_E['213'] = '<img localsrc="81">'; 
    $EMOJI_E['214'] = '<img localsrc="54">'; 
    $EMOJI_E['215'] = '<img localsrc="218">'; 
    $EMOJI_E['216'] = '<img localsrc="279">'; 
    $EMOJI_E['217'] = '<img localsrc="807">'; 
    $EMOJI_E['218'] = '<img localsrc="82">'; 
    $EMOJI_E['219'] = '<img localsrc="1">'; 
    $EMOJI_E['220'] = 'ã÷'; 
    $EMOJI_E['221'] = '<img localsrc="387">'; 
    $EMOJI_E['222'] = 'çá'; 
    $EMOJI_E['223'] = '<img localsrc="386">'; 
    $EMOJI_E['224'] = '<img localsrc="808">'; 
    $EMOJI_E['225'] = '<img localsrc="809">'; 
    $EMOJI_E['226'] = '<img localsrc="377">'; 
    $EMOJI_E['227'] = '<img localsrc="810">'; 
    $EMOJI_E['228'] = '<img localsrc="342">'; 
    $EMOJI_E['229'] = '<img localsrc="53">'; 
    $EMOJI_E['230'] = '<img localsrc="241">'; 
    $EMOJI_E['231'] = '<img localsrc="113">'; 
    $EMOJI_E['232'] = '<img localsrc="739">'; 
    $EMOJI_E['233'] = '<img localsrc="434">'; 
    $EMOJI_E['234'] = '<img localsrc="811">'; 
    $EMOJI_E['235'] = '<img localsrc="133">'; 
    $EMOJI_E['236'] = '<img localsrc="235">'; 
    $EMOJI_E['237'] = '<img localsrc="244">'; 
    $EMOJI_E['238'] = '<img localsrc="239">'; 
    $EMOJI_E['239'] = '<img localsrc="400">'; 
    $EMOJI_E['240'] = '<img localsrc="429">'; 
    $EMOJI_E['241'] = '<img localsrc="424">'; 
    $EMOJI_E['242'] = '<img localsrc="812">'; 
    $EMOJI_E['243'] = '<img localsrc="78">'; 
    $EMOJI_E['244'] = '<img localsrc="252">'; 
    $EMOJI_E['245'] = '<img localsrc="203">'; 
    $EMOJI_E['246'] = '<img localsrc="454">'; 
    $EMOJI_E['247'] = '<img localsrc="814">'; 
    $EMOJI_E['248'] = '<img localsrc="248">'; 
    $EMOJI_E['249'] = '<img localsrc="758">'; 
    $EMOJI_E['250'] = '<img localsrc="12">'; 
    $EMOJI_E['251'] = '<img localsrc="350">'; 
}else{
    $EMOJI_E['0'] = '<img icon="44">'; 
    $EMOJI_E['1'] = '<img icon="107">'; 
    $EMOJI_E['2'] = '<img icon="95">'; 
    $EMOJI_E['3'] = '<img icon="191">'; 
    $EMOJI_E['4'] = '<img icon="16">'; 
    $EMOJI_E['5'] = '<img icon="190">'; 
    $EMOJI_E['6'] = '<img icon="305">'; 
    $EMOJI_E['7'] = '<img icon="481">'; 
    $EMOJI_E['8'] = '<img icon="192">'; 
    $EMOJI_E['9'] = '<img icon="193">'; 
    $EMOJI_E['10'] = '<img icon="194">'; 
    $EMOJI_E['11'] = '<img icon="195">'; 
    $EMOJI_E['12'] = '<img icon="196">'; 
    $EMOJI_E['13'] = '<img icon="197">'; 
    $EMOJI_E['14'] = '<img icon="198">'; 
    $EMOJI_E['15'] = '<img icon="199">'; 
    $EMOJI_E['16'] = '<img icon="200">'; 
    $EMOJI_E['17'] = '<img icon="201">'; 
    $EMOJI_E['18'] = '<img icon="202">'; 
    $EMOJI_E['19'] = '<img icon="203">'; 
    $EMOJI_E['20'] = '<img icon="218">'; 
    $EMOJI_E['21'] = '<img icon="45">'; 
    $EMOJI_E['22'] = '<img icon="306">'; 
    $EMOJI_E['23'] = '<img icon="220">'; 
    $EMOJI_E['24'] = '<img icon="219">'; 
    $EMOJI_E['25'] = '<img icon="421">'; 
    $EMOJI_E['26'] = '<img icon="307">'; 
    $EMOJI_E['27'] = '<img icon="222">'; 
    $EMOJI_E['28'] = '<img icon="308">'; 
    $EMOJI_E['29'] = '<img icon="172">'; 
    $EMOJI_E['30'] = '<img icon="341">'; 
    $EMOJI_E['31'] = '<img icon="217">'; 
    $EMOJI_E['32'] = '<img icon="125">'; 
    $EMOJI_E['33'] = '<img icon="125">'; 
    $EMOJI_E['34'] = '<img icon="216">'; 
    $EMOJI_E['35'] = '<img icon="379">'; 
    $EMOJI_E['36'] = '<img icon="168">'; 
    $EMOJI_E['37'] = '<img icon="112">'; 
    $EMOJI_E['38'] = '<img icon="156">'; 
    $EMOJI_E['39'] = '<img icon="375">'; 
    $EMOJI_E['40'] = '<img icon="376">'; 
    $EMOJI_E['41'] = '<img icon="212">'; 
    $EMOJI_E['42'] = '<img icon="205">'; 
    $EMOJI_E['43'] = '<img icon="378">'; 
    $EMOJI_E['44'] = '<img icon="206">'; 
    $EMOJI_E['45'] = '<img icon="213">'; 
    $EMOJI_E['46'] = '<img icon="208">'; 
    $EMOJI_E['47'] = '<img icon="99">'; 
    $EMOJI_E['48'] = '<img icon="207">'; 
    $EMOJI_E['49'] = '<img icon="146">'; 
    $EMOJI_E['50'] = '<img icon="93">'; 
    $EMOJI_E['51'] = '<img icon="52">'; 
    $EMOJI_E['52'] = '<img icon="65">'; 
    $EMOJI_E['53'] = '<img icon="245">'; 
    $EMOJI_E['54'] = '<img icon="124">'; 
    $EMOJI_E['55'] = '<img icon="104">'; 
    $EMOJI_E['56'] = '<img icon="289">'; 
    $EMOJI_E['57'] = '<img icon="110">'; 
    $EMOJI_E['58'] = '<img icon="70">'; 
    $EMOJI_E['59'] = '<img icon="223">'; 
    $EMOJI_E['60'] = '<img icon="294">'; 
    $EMOJI_E['61'] = '<img icon="309">'; 
    $EMOJI_E['62'] = '<img icon="310">'; 
    $EMOJI_E['63'] = '<img icon="311">'; 
    $EMOJI_E['64'] = '<img icon="106">'; 
    $EMOJI_E['65'] = '<img icon="176">'; 
    $EMOJI_E['66'] = '<img icon="177">'; 
    $EMOJI_E['67'] = '<img icon="94">'; 
    $EMOJI_E['68'] = '<img icon="83">'; 
    $EMOJI_E['69'] = '<img icon="122">'; 
    $EMOJI_E['70'] = '<img icon="312">'; 
    $EMOJI_E['71'] = '<img icon="144">'; 
    $EMOJI_E['72'] = '<img icon="313">'; 
    $EMOJI_E['73'] = '<img icon="85">'; 
    $EMOJI_E['74'] = '<img icon="161">'; 
    $EMOJI_E['75'] = '<img icon="56">'; 
    $EMOJI_E['76'] = '<img icon="288">'; 
    $EMOJI_E['77'] = '<img icon="232">'; 
    $EMOJI_E['78'] = '<img icon="300">'; 
    $EMOJI_E['79'] = '<img icon="414">'; 
    $EMOJI_E['80'] = '<img icon="314">'; 
    $EMOJI_E['81'] = '<img icon="315">'; 
    $EMOJI_E['82'] = '<img icon="316">'; 
    $EMOJI_E['83'] = '<img icon="317">'; 
    $EMOJI_E['84'] = '<img icon="318">'; 
    $EMOJI_E['85'] = '<img icon="817">'; 
    $EMOJI_E['86'] = '<img icon="319">'; 
    $EMOJI_E['87'] = '<img icon="320">'; 
    $EMOJI_E['88'] = '<img icon="43">'; 
    $EMOJI_E['89'] = '<img icon="42">'; 
    $EMOJI_E['90'] = '<img icon="728">'; 
    $EMOJI_E['91'] = '<img icon="729">'; 
    $EMOJI_E['92'] = '<img icon="116">'; 
    $EMOJI_E['93'] = '<img icon="178">'; 
    $EMOJI_E['94'] = '<img icon="321">'; 
    $EMOJI_E['95'] = '<img icon="322">'; 
    $EMOJI_E['96'] = '<img icon="323">'; 
    $EMOJI_E['97'] = '<img icon="15">'; 
    $EMOJI_E['98'] = '<img icon="47">'; 
    $EMOJI_E['99'] = '<img icon="134">'; 
    $EMOJI_E['100'] = '<img icon="251">'; 
    $EMOJI_E['101'] = '<img icon="169">'; 
    $EMOJI_E['102'] = '<img icon="234">'; 
    $EMOJI_E['103'] = '<img icon="71">'; 
    $EMOJI_E['104'] = '<img icon="226">'; 
    $EMOJI_E['105'] = '<img icon="233">'; 
    $EMOJI_E['106'] = '<img icon="508">'; 
    $EMOJI_E['107'] = '<img icon="80">'; 
    $EMOJI_E['108'] = ''; 
    $EMOJI_E['109'] = '<img icon="227">'; 
    $EMOJI_E['110'] = '<img icon="63">'; 
    $EMOJI_E['111'] = '<img icon="808">'; 
    $EMOJI_E['112'] = '<img icon="64">'; 
    $EMOJI_E['113'] = '<img icon="46">'; 
    $EMOJI_E['114'] = '<img icon="513">'; 
    $EMOJI_E['115'] = '<img icon="784">'; 
    $EMOJI_E['116'] = '<img icon="166">'; 
    $EMOJI_E['117'] = 'i'; 
    $EMOJI_E['118'] = 'i'; 
    $EMOJI_E['119'] = '<img icon="108">'; 
    $EMOJI_E['120'] = 'D'; 
    $EMOJI_E['121'] = 'D'; 
    $EMOJI_E['122'] = '<img icon="109">'; 
    $EMOJI_E['123'] = '<img icon="299">'; 
    $EMOJI_E['124'] = '<img icon="385">'; 
    $EMOJI_E['125'] = '<img icon="120">'; 
    $EMOJI_E['126'] = '<img icon="118">'; 
    $EMOJI_E['127'] = '<img icon="324">'; 
    $EMOJI_E['128'] = '<img icon="119">'; 
    $EMOJI_E['129'] = '<img icon="334">'; 
    $EMOJI_E['130'] = '<img icon="730">'; 
    $EMOJI_E['131'] = 'F'; 
    $EMOJI_E['132'] = '#'; 
    $EMOJI_E['133'] = 'Q'; 
    $EMOJI_E['134'] = '<img icon="180">'; 
    $EMOJI_E['135'] = '<img icon="181">'; 
    $EMOJI_E['136'] = '<img icon="182">'; 
    $EMOJI_E['137'] = '<img icon="183">'; 
    $EMOJI_E['138'] = '<img icon="184">'; 
    $EMOJI_E['139'] = '<img icon="185">'; 
    $EMOJI_E['140'] = '<img icon="186">'; 
    $EMOJI_E['141'] = '<img icon="187">'; 
    $EMOJI_E['142'] = '<img icon="188">'; 
    $EMOJI_E['143'] = '<img icon="325">'; 
    $EMOJI_E['144'] = '<img icon="51">'; 
    $EMOJI_E['145'] = '<img icon="328">'; 
    $EMOJI_E['146'] = '<img icon="265">'; 
    $EMOJI_E['147'] = '<img icon="266">'; 
    $EMOJI_E['148'] = '<img icon="257">'; 
    $EMOJI_E['149'] = '<img icon="258">'; 
    $EMOJI_E['150'] = '<img icon="260">'; 
    $EMOJI_E['151'] = '<img icon="259">'; 
    $EMOJI_E['152'] = '<img icon="327">'; 
    $EMOJI_E['153'] = '<img icon="731">'; 
    $EMOJI_E['154'] = '<img icon="343">'; 
    $EMOJI_E['155'] = '<img icon="224">'; 
    $EMOJI_E['156'] = '<img icon="19">'; 
    $EMOJI_E['157'] = '<img icon="273">'; 
    $EMOJI_E['158'] = '<img icon="420">'; 
    $EMOJI_E['159'] = '<img icon="77">'; 
    $EMOJI_E['160'] = '<img icon="262">'; 
    $EMOJI_E['161'] = '<img icon="281">'; 
    $EMOJI_E['162'] = '<img icon="268">'; 
    $EMOJI_E['163'] = '<img icon="291">'; 
    $EMOJI_E['164'] = '<img icon="732">'; 
    $EMOJI_E['165'] = '<img icon="261">'; 
    $EMOJI_E['166'] = '<img icon="2">'; 
    $EMOJI_E['167'] = '<img icon="733">'; 
    $EMOJI_E['168'] = '<img icon="734">'; 
    $EMOJI_E['169'] = '<img icon="329">'; 
    $EMOJI_E['170'] = '<img icon="330">'; 
    $EMOJI_E['171'] = '<img icon="263">'; 
    $EMOJI_E['172'] = '<img icon="282">'; 
    $EMOJI_E['173'] = '<img icon="810">'; 
    $EMOJI_E['174'] = '<img icon="735">'; 
    $EMOJI_E['175'] = '<img icon="326">'; 
    $EMOJI_E['176'] = 'Éø'; 
    $EMOJI_E['177'] = 'Éø'; 
    $EMOJI_E['178'] = '<img icon="335">'; 
    $EMOJI_E['179'] = '<img icon="290">'; 
    $EMOJI_E['180'] = '<img icon="295">'; 
    $EMOJI_E['181'] = '<img icon="805">'; 
    $EMOJI_E['182'] = '<img icon="221">'; 
    $EMOJI_E['183'] = '<img icon="48">'; 
    $EMOJI_E['184'] = ''; 
    $EMOJI_E['185'] = '<img icon="233">'; 
    $EMOJI_E['186'] = '<img icon="337">'; 
    $EMOJI_E['187'] = '<img icon="806">'; 
    $EMOJI_E['188'] = '<img icon="152">'; 
    $EMOJI_E['189'] = '<img icon="149">'; 
    $EMOJI_E['190'] = '<img icon="354">'; 
    $EMOJI_E['191'] = '<img icon="72">'; 
    $EMOJI_E['192'] = '<img icon="58">'; 
    $EMOJI_E['193'] = '<img icon="215">'; 
    $EMOJI_E['194'] = '<img icon="423">'; 
    $EMOJI_E['195'] = '<img icon="25">'; 
    $EMOJI_E['196'] = '<img icon="443">'; 
    $EMOJI_E['197'] = '<img icon="454">'; 
    $EMOJI_E['198'] = '<img icon="351">'; 
    $EMOJI_E['199'] = '<img icon="351">'; 
    $EMOJI_E['200'] = '<img icon="779">'; 
    $EMOJI_E['201'] = '<img icon="789">'; 
    $EMOJI_E['202'] = '<img icon="349">'; 
    $EMOJI_E['203'] = '<img icon="287">'; 
    $EMOJI_E['204'] = '<img icon="264">'; 
    $EMOJI_E['205'] = '<img icon="348">'; 
    $EMOJI_E['206'] = '<img icon="257">'; 
    $EMOJI_E['207'] = '<img icon="260">'; 
    $EMOJI_E['208'] = '<img icon="783">'; 
    $EMOJI_E['209'] = '<img icon="259">'; 
    $EMOJI_E['210'] = '<img icon="791">'; 
    $EMOJI_E['211'] = ''; 
    $EMOJI_E['212'] = '<img icon="143">'; 
    $EMOJI_E['213'] = '<img icon="81">'; 
    $EMOJI_E['214'] = '<img icon="54">'; 
    $EMOJI_E['215'] = '<img icon="218">'; 
    $EMOJI_E['216'] = '<img icon="279">'; 
    $EMOJI_E['217'] = '<img icon="807">'; 
    $EMOJI_E['218'] = '<img icon="82">'; 
    $EMOJI_E['219'] = '<img icon="1">'; 
    $EMOJI_E['220'] = 'ã÷'; 
    $EMOJI_E['221'] = '<img icon="387">'; 
    $EMOJI_E['222'] = 'çá'; 
    $EMOJI_E['223'] = '<img icon="386">'; 
    $EMOJI_E['224'] = '<img icon="808">'; 
    $EMOJI_E['225'] = '<img icon="809">'; 
    $EMOJI_E['226'] = '<img icon="377">'; 
    $EMOJI_E['227'] = '<img icon="810">'; 
    $EMOJI_E['228'] = '<img icon="342">'; 
    $EMOJI_E['229'] = '<img icon="53">'; 
    $EMOJI_E['230'] = '<img icon="241">'; 
    $EMOJI_E['231'] = '<img icon="113">'; 
    $EMOJI_E['232'] = '<img icon="739">'; 
    $EMOJI_E['233'] = '<img icon="434">'; 
    $EMOJI_E['234'] = '<img icon="811">'; 
    $EMOJI_E['235'] = '<img icon="133">'; 
    $EMOJI_E['236'] = '<img icon="235">'; 
    $EMOJI_E['237'] = '<img icon="244">'; 
    $EMOJI_E['238'] = '<img icon="239">'; 
    $EMOJI_E['239'] = '<img icon="400">'; 
    $EMOJI_E['240'] = '<img icon="429">'; 
    $EMOJI_E['241'] = '<img icon="424">'; 
    $EMOJI_E['242'] = '<img icon="812">'; 
    $EMOJI_E['243'] = '<img icon="78">'; 
    $EMOJI_E['244'] = '<img icon="252">'; 
    $EMOJI_E['245'] = '<img icon="203">'; 
    $EMOJI_E['246'] = '<img icon="454">'; 
    $EMOJI_E['247'] = '<img icon="814">'; 
    $EMOJI_E['248'] = '<img icon="248">'; 
    $EMOJI_E['249'] = '<img icon="758">'; 
    $EMOJI_E['250'] = '<img icon="12">'; 
    $EMOJI_E['251'] = '<img icon="350">'; 
}


//willcom
$EMOJI_W[0] =  '¯ü';
$EMOJI_W[1] =  '¯†';
$EMOJI_W[2] =  '¯°';
$EMOJI_W[3] =  '¯¢';
$EMOJI_W[4] =  '¯£';
$EMOJI_W[5] =  '¯§';
$EMOJI_W[6] =  '¯•';
$EMOJI_W[7] =  '¯¶';
$EMOJI_W[8] =  '¯ß';
$EMOJI_W[9] =  '¯®';
$EMOJI_W[10] = '¯©';
$EMOJI_W[11] = '¯™';
$EMOJI_W[12] = '¯´';
$EMOJI_W[13] = '¯¨';
$EMOJI_W[14] = '¯≠';
$EMOJI_W[15] = '¯Æ';
$EMOJI_W[16] = '¯Ø';
$EMOJI_W[17] = '¯∞';
$EMOJI_W[18] = '¯±';
$EMOJI_W[19] = '¯≤';
$EMOJI_W[20] = '¯≥';
$EMOJI_W[21] = '¯¥';
$EMOJI_W[22] = '¯µ';
$EMOJI_W[23] = '¯∂';
$EMOJI_W[24] = '¯∑';
$EMOJI_W[25] = '¯∏';
$EMOJI_W[26] = '¯π';
$EMOJI_W[27] = '¯∫';
$EMOJI_W[28] = '¯ª';
$EMOJI_W[29] = '¯º';
$EMOJI_W[30] = '¯Ω';
$EMOJI_W[31] = '¯æ';
$EMOJI_W[32] = '¯ø';
$EMOJI_W[33] = '¯¿';
$EMOJI_W[34] = '¯¡';
$EMOJI_W[35] = '¯¬';
$EMOJI_W[36] = '¯√';
$EMOJI_W[37] = '¯ƒ';
$EMOJI_W[38] = '¯≈';
$EMOJI_W[39] = '¯∆';
$EMOJI_W[40] = '¯«';
$EMOJI_W[41] = '¯»';
$EMOJI_W[42] = '¯…';
$EMOJI_W[43] = '¯ ';
$EMOJI_W[44] = '¯À';
$EMOJI_W[45] = '¯Ã';
$EMOJI_W[46] = '¯Õ';
$EMOJI_W[47] = '¯Œ';
$EMOJI_W[48] = '¯œ';
$EMOJI_W[49] = '¯–';
$EMOJI_W[50] = '¯—';
$EMOJI_W[51] = '¯“';
$EMOJI_W[52] = '¯”';
$EMOJI_W[53] = '¯‘';
$EMOJI_W[54] = '¯’';
$EMOJI_W[55] = '¯÷';
$EMOJI_W[56] = '¯◊';
$EMOJI_W[57] = '¯ÿ';
$EMOJI_W[58] = '¯Ÿ';
$EMOJI_W[59] = '¯⁄';
$EMOJI_W[60] = '¯€';
$EMOJI_W[61] = '¯‹';
$EMOJI_W[62] = '¯›';
$EMOJI_W[63] = '¯ﬁ';
$EMOJI_W[64] = '¯ﬂ';
$EMOJI_W[65] = '¯‡';
$EMOJI_W[66] = '¯·';
$EMOJI_W[67] = '¯‚';
$EMOJI_W[68] = '¯„';
$EMOJI_W[69] = '¯‰';
$EMOJI_W[70] = '¯Â';
$EMOJI_W[71] = '¯Ê';
$EMOJI_W[72] = '¯Á';
$EMOJI_W[73] = '¯Ë';
$EMOJI_W[74] = '¯È';
$EMOJI_W[75] = '¯Í';
$EMOJI_W[76] = '¯Î';
$EMOJI_W[77] = '¯Ï';
$EMOJI_W[78] = '¯Ì';
$EMOJI_W[79] = '¯Ó';
$EMOJI_W[80] = '¯Ô';
$EMOJI_W[81] = '¯';
$EMOJI_W[82] = '¯Ò';
$EMOJI_W[83] = '¯Ú';
$EMOJI_W[84] = '¯Û';
$EMOJI_W[85] = '¯Ù';
$EMOJI_W[86] = '¯ı';
$EMOJI_W[87] = '¯ˆ';
$EMOJI_W[88] = '¯˜';
$EMOJI_W[89] = '¯¯';
$EMOJI_W[90] = '¯˘';
$EMOJI_W[91] = '¯˙';
$EMOJI_W[92] = '¯˚';
$EMOJI_W[93] = '¯¸';
$EMOJI_W[94] = '˘@';
$EMOJI_W[95] = '˘A';
$EMOJI_W[96] = '˘B';
$EMOJI_W[97] = '˘C';
$EMOJI_W[98] = '˘D';
$EMOJI_W[99] = '˘E';
$EMOJI_W[100] ='˘F';
$EMOJI_W[101] ='˘G';
$EMOJI_W[102] ='˘H';
$EMOJI_W[103] ='˘I';
$EMOJI_W[104] ='˘P';
$EMOJI_W[105] ='˘Q';
$EMOJI_W[106] ='˘R';
$EMOJI_W[107] ='˘U';
$EMOJI_W[108] ='˘V';
$EMOJI_W[109] ='˘W';
$EMOJI_W[110] ='˘[';
$EMOJI_W[111] ='˘\\';
$EMOJI_W[112] ='˘]';
$EMOJI_W[113] ='˘^';
$EMOJI_W[114] ='˘r';
$EMOJI_W[115] ='˘s';
$EMOJI_W[116] ='˘t';
$EMOJI_W[117] ='˘u';
$EMOJI_W[118] ='˘v';
$EMOJI_W[119] ='˘w';
$EMOJI_W[120] ='˘x';
$EMOJI_W[121] ='˘y';
$EMOJI_W[122] ='˘z';
$EMOJI_W[123] ='˘{';
$EMOJI_W[124] ='˘|';
$EMOJI_W[125] ='˘}';
$EMOJI_W[126] ='˘~';
$EMOJI_W[127] ='˘Ä';
$EMOJI_W[128] ='˘Å';
$EMOJI_W[129] ='˘Ç';
$EMOJI_W[130] ='˘É';
$EMOJI_W[131] ='˘Ñ';
$EMOJI_W[132] ='˘Ö';
$EMOJI_W[133] ='˘Ü';
$EMOJI_W[134] ='˘á';
$EMOJI_W[135] ='˘à';
$EMOJI_W[136] ='˘â';
$EMOJI_W[137] ='˘ä';
$EMOJI_W[138] ='˘ã';
$EMOJI_W[139] ='˘å';
$EMOJI_W[140] ='˘ç';
$EMOJI_W[141] ='˘é';
$EMOJI_W[142] ='˘è';
$EMOJI_W[143] ='˘ê';
$EMOJI_W[144] ='˘ë';
$EMOJI_W[145] ='˘í';
$EMOJI_W[146] ='˘ì';
$EMOJI_W[147] ='˘î';
$EMOJI_W[148] ='˘ï';
$EMOJI_W[149] ='˘ñ';
$EMOJI_W[150] ='˘ó';
$EMOJI_W[151] ='˘ò';
$EMOJI_W[152] ='˘ô';
$EMOJI_W[153] ='˘ö';
$EMOJI_W[154] ='˘õ';
$EMOJI_W[155] ='˘ú';
$EMOJI_W[156] ='˘ù';
$EMOJI_W[157] ='˘û';
$EMOJI_W[158] ='˘ü';
$EMOJI_W[159] ='˘†';
$EMOJI_W[160] ='˘°';
$EMOJI_W[161] ='˘¢';
$EMOJI_W[162] ='˘£';
$EMOJI_W[163] ='˘§';
$EMOJI_W[164] ='˘•';
$EMOJI_W[165] ='˘¶';
$EMOJI_W[166] ='˘ß';
$EMOJI_W[167] ='˘®';
$EMOJI_W[168] ='˘©';
$EMOJI_W[169] ='˘™';
$EMOJI_W[170] ='˘´';
$EMOJI_W[171] ='˘¨';
$EMOJI_W[172] ='˘≠';
$EMOJI_W[173] ='˘Æ';
$EMOJI_W[174] ='˘Ø';
$EMOJI_W[175] ='˘∞';
$EMOJI_W[176] ='˘±';
$EMOJI_W[177] ='˘≤';
$EMOJI_W[178] ='˘≥';
$EMOJI_W[179] ='˘¥';
$EMOJI_W[180] ='˘µ';
$EMOJI_W[181] ='˘∂';
$EMOJI_W[182] ='˘∑';
$EMOJI_W[183] ='˘∏';
$EMOJI_W[184] ='˘π';
$EMOJI_W[185] ='˘∫';
$EMOJI_W[186] ='˘ª';
$EMOJI_W[187] ='˘º';
$EMOJI_W[188] ='˘Ω';
$EMOJI_W[189] ='˘æ';
$EMOJI_W[190] ='˘ø';
$EMOJI_W[191] ='˘¿';
$EMOJI_W[192] ='˘¡';
$EMOJI_W[193] ='˘¬';
$EMOJI_W[194] ='˘√';
$EMOJI_W[195] ='˘ƒ';
$EMOJI_W[196] ='˘≈';
$EMOJI_W[197] ='˘∆';
$EMOJI_W[198] ='˘«';
$EMOJI_W[199] ='˘»';
$EMOJI_W[200] ='˘…';
$EMOJI_W[201] ='˘ ';
$EMOJI_W[202] ='˘À';
$EMOJI_W[203] ='˘Ã';
$EMOJI_W[204] ='˘Õ';
$EMOJI_W[205] ='˘Œ';
$EMOJI_W[206] ='˘œ';
$EMOJI_W[207] ='˘–';
$EMOJI_W[208] ='˘—';
$EMOJI_W[209] ='˘“';
$EMOJI_W[210] ='˘”';
$EMOJI_W[211] ='˘‘';
$EMOJI_W[212] ='˘’';
$EMOJI_W[213] ='˘÷';
$EMOJI_W[214] ='˘◊';
$EMOJI_W[215] ='˘ÿ';
$EMOJI_W[216] ='˘Ÿ';
$EMOJI_W[217] ='˘⁄';
$EMOJI_W[218] ='˘€';
$EMOJI_W[219] ='˘‹';
$EMOJI_W[220] ='˘›';
$EMOJI_W[221] ='˘ﬁ';
$EMOJI_W[222] ='˘ﬂ';
$EMOJI_W[223] ='˘‡';
$EMOJI_W[224] ='˘·';
$EMOJI_W[225] ='˘‚';
$EMOJI_W[226] ='˘„';
$EMOJI_W[227] ='˘‰';
$EMOJI_W[228] ='˘Â';
$EMOJI_W[229] ='˘Ê';
$EMOJI_W[230] ='˘Á';
$EMOJI_W[231] ='˘Ë';
$EMOJI_W[232] ='˘È';
$EMOJI_W[233] ='˘Í';
$EMOJI_W[234] ='˘Î';
$EMOJI_W[235] ='˘Ï';
$EMOJI_W[236] ='˘Ì';
$EMOJI_W[237] ='˘Ó';
$EMOJI_W[238] ='˘Ô';
$EMOJI_W[239] ='˘';
$EMOJI_W[240] ='˘Ò';
$EMOJI_W[241] ='˘Ú';
$EMOJI_W[242] ='˘Û';
$EMOJI_W[243] ='˘Ù';
$EMOJI_W[244] ='˘ı';
$EMOJI_W[245] ='˘ˆ';
$EMOJI_W[246] ='˘˜';
$EMOJI_W[247] ='˘¯';
$EMOJI_W[248] ='˘˘';
$EMOJI_W[249] ='˘˙';
$EMOJI_W[250] ='˘˚';
$EMOJI_W[251] ='˘¸';
?>
